/**
 * This class is generated by jOOQ
 */
package us.fok.lenzenslijper.models.jooq.routines;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class _PostgisStats extends org.jooq.impl.AbstractRoutine<java.lang.String> {

	private static final long serialVersionUID = -916006882;

	/**
	 * The parameter <code>public._postgis_stats.RETURN_VALUE</code>.
	 */
	public static final org.jooq.Parameter<java.lang.String> RETURN_VALUE = createParameter("RETURN_VALUE", org.jooq.impl.SQLDataType.CLOB);

	/**
	 * The parameter <code>public._postgis_stats.tbl</code>.
	 */
	public static final org.jooq.Parameter<java.lang.Object> TBL = createParameter("tbl", org.jooq.impl.DefaultDataType.getDefaultDataType("regclass"));

	/**
	 * The parameter <code>public._postgis_stats.att_name</code>.
	 */
	public static final org.jooq.Parameter<java.lang.String> ATT_NAME = createParameter("att_name", org.jooq.impl.SQLDataType.CLOB);

	/**
	 * The parameter <code>public._postgis_stats._3</code>.
	 */
	public static final org.jooq.Parameter<java.lang.String> _3 = createParameter("_3", org.jooq.impl.SQLDataType.CLOB);

	/**
	 * Create a new routine call instance
	 */
	public _PostgisStats() {
		super("_postgis_stats", us.fok.lenzenslijper.models.jooq.Public.PUBLIC, org.jooq.impl.SQLDataType.CLOB);

		setReturnParameter(RETURN_VALUE);
		addInParameter(TBL);
		addInParameter(ATT_NAME);
		addInParameter(_3);
	}

	/**
	 * Set the <code>tbl</code> parameter IN value to the routine
	 */
	public void setTbl(java.lang.Object value) {
		setValue(us.fok.lenzenslijper.models.jooq.routines._PostgisStats.TBL, value);
	}

	/**
	 * Set the <code>tbl</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public void setTbl(org.jooq.Field<java.lang.Object> field) {
		setField(TBL, field);
	}

	/**
	 * Set the <code>att_name</code> parameter IN value to the routine
	 */
	public void setAttName(java.lang.String value) {
		setValue(us.fok.lenzenslijper.models.jooq.routines._PostgisStats.ATT_NAME, value);
	}

	/**
	 * Set the <code>att_name</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public void setAttName(org.jooq.Field<java.lang.String> field) {
		setField(ATT_NAME, field);
	}

	/**
	 * Set the <code>_3</code> parameter IN value to the routine
	 */
	public void set__3(java.lang.String value) {
		setValue(us.fok.lenzenslijper.models.jooq.routines._PostgisStats._3, value);
	}

	/**
	 * Set the <code>_3</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public void set__3(org.jooq.Field<java.lang.String> field) {
		setField(_3, field);
	}
}
