/**
 * This class is generated by jOOQ
 */
package us.fok.lenzenslijper.models.jooq.routines;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class _PostgisDeprecate extends org.jooq.impl.AbstractRoutine<java.lang.Void> {

	private static final long serialVersionUID = -661954862;

	/**
	 * The parameter <code>public._postgis_deprecate.oldname</code>.
	 */
	public static final org.jooq.Parameter<java.lang.String> OLDNAME = createParameter("oldname", org.jooq.impl.SQLDataType.CLOB);

	/**
	 * The parameter <code>public._postgis_deprecate.newname</code>.
	 */
	public static final org.jooq.Parameter<java.lang.String> NEWNAME = createParameter("newname", org.jooq.impl.SQLDataType.CLOB);

	/**
	 * The parameter <code>public._postgis_deprecate.version</code>.
	 */
	public static final org.jooq.Parameter<java.lang.String> VERSION = createParameter("version", org.jooq.impl.SQLDataType.CLOB);

	/**
	 * Create a new routine call instance
	 */
	public _PostgisDeprecate() {
		super("_postgis_deprecate", us.fok.lenzenslijper.models.jooq.Public.PUBLIC);

		addInParameter(OLDNAME);
		addInParameter(NEWNAME);
		addInParameter(VERSION);
	}

	/**
	 * Set the <code>oldname</code> parameter IN value to the routine
	 */
	public void setOldname(java.lang.String value) {
		setValue(us.fok.lenzenslijper.models.jooq.routines._PostgisDeprecate.OLDNAME, value);
	}

	/**
	 * Set the <code>newname</code> parameter IN value to the routine
	 */
	public void setNewname(java.lang.String value) {
		setValue(us.fok.lenzenslijper.models.jooq.routines._PostgisDeprecate.NEWNAME, value);
	}

	/**
	 * Set the <code>version</code> parameter IN value to the routine
	 */
	public void setVersion(java.lang.String value) {
		setValue(us.fok.lenzenslijper.models.jooq.routines._PostgisDeprecate.VERSION, value);
	}
}
