/**
 * This class is generated by jOOQ
 */
package us.fok.lenzenslijper.models.jooq.routines;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class _PostgisJoinSelectivity extends org.jooq.impl.AbstractRoutine<java.lang.Double> {

	private static final long serialVersionUID = -740634944;

	/**
	 * The parameter <code>public._postgis_join_selectivity.RETURN_VALUE</code>.
	 */
	public static final org.jooq.Parameter<java.lang.Double> RETURN_VALUE = createParameter("RETURN_VALUE", org.jooq.impl.SQLDataType.DOUBLE);

	/**
	 * The parameter <code>public._postgis_join_selectivity._1</code>.
	 */
	public static final org.jooq.Parameter<java.lang.Object> _1 = createParameter("_1", org.jooq.impl.DefaultDataType.getDefaultDataType("regclass"));

	/**
	 * The parameter <code>public._postgis_join_selectivity._2</code>.
	 */
	public static final org.jooq.Parameter<java.lang.String> _2 = createParameter("_2", org.jooq.impl.SQLDataType.CLOB);

	/**
	 * The parameter <code>public._postgis_join_selectivity._3</code>.
	 */
	public static final org.jooq.Parameter<java.lang.Object> _3 = createParameter("_3", org.jooq.impl.DefaultDataType.getDefaultDataType("regclass"));

	/**
	 * The parameter <code>public._postgis_join_selectivity._4</code>.
	 */
	public static final org.jooq.Parameter<java.lang.String> _4 = createParameter("_4", org.jooq.impl.SQLDataType.CLOB);

	/**
	 * The parameter <code>public._postgis_join_selectivity._5</code>.
	 */
	public static final org.jooq.Parameter<java.lang.String> _5 = createParameter("_5", org.jooq.impl.SQLDataType.CLOB);

	/**
	 * Create a new routine call instance
	 */
	public _PostgisJoinSelectivity() {
		super("_postgis_join_selectivity", us.fok.lenzenslijper.models.jooq.Public.PUBLIC, org.jooq.impl.SQLDataType.DOUBLE);

		setReturnParameter(RETURN_VALUE);
		addInParameter(_1);
		addInParameter(_2);
		addInParameter(_3);
		addInParameter(_4);
		addInParameter(_5);
	}

	/**
	 * Set the <code>_1</code> parameter IN value to the routine
	 */
	public void set__1(java.lang.Object value) {
		setValue(us.fok.lenzenslijper.models.jooq.routines._PostgisJoinSelectivity._1, value);
	}

	/**
	 * Set the <code>_1</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public void set__1(org.jooq.Field<java.lang.Object> field) {
		setField(_1, field);
	}

	/**
	 * Set the <code>_2</code> parameter IN value to the routine
	 */
	public void set__2(java.lang.String value) {
		setValue(us.fok.lenzenslijper.models.jooq.routines._PostgisJoinSelectivity._2, value);
	}

	/**
	 * Set the <code>_2</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public void set__2(org.jooq.Field<java.lang.String> field) {
		setField(_2, field);
	}

	/**
	 * Set the <code>_3</code> parameter IN value to the routine
	 */
	public void set__3(java.lang.Object value) {
		setValue(us.fok.lenzenslijper.models.jooq.routines._PostgisJoinSelectivity._3, value);
	}

	/**
	 * Set the <code>_3</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public void set__3(org.jooq.Field<java.lang.Object> field) {
		setField(_3, field);
	}

	/**
	 * Set the <code>_4</code> parameter IN value to the routine
	 */
	public void set__4(java.lang.String value) {
		setValue(us.fok.lenzenslijper.models.jooq.routines._PostgisJoinSelectivity._4, value);
	}

	/**
	 * Set the <code>_4</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public void set__4(org.jooq.Field<java.lang.String> field) {
		setField(_4, field);
	}

	/**
	 * Set the <code>_5</code> parameter IN value to the routine
	 */
	public void set__5(java.lang.String value) {
		setValue(us.fok.lenzenslijper.models.jooq.routines._PostgisJoinSelectivity._5, value);
	}

	/**
	 * Set the <code>_5</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public void set__5(org.jooq.Field<java.lang.String> field) {
		setField(_5, field);
	}
}
