/**
 * This class is generated by jOOQ
 */
package us.fok.lenzenslijper.models.jooq.routines;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Dropoverviewconstraints1 extends org.jooq.impl.AbstractRoutine<java.lang.Boolean> {

	private static final long serialVersionUID = 1449082425;

	/**
	 * The parameter <code>public.dropoverviewconstraints.RETURN_VALUE</code>.
	 */
	public static final org.jooq.Parameter<java.lang.Boolean> RETURN_VALUE = createParameter("RETURN_VALUE", org.jooq.impl.SQLDataType.BOOLEAN);

	/**
	 * The parameter <code>public.dropoverviewconstraints.ovschema</code>.
	 */
	public static final org.jooq.Parameter<java.lang.String> OVSCHEMA = createParameter("ovschema", org.jooq.impl.SQLDataType.VARCHAR);

	/**
	 * The parameter <code>public.dropoverviewconstraints.ovtable</code>.
	 */
	public static final org.jooq.Parameter<java.lang.String> OVTABLE = createParameter("ovtable", org.jooq.impl.SQLDataType.VARCHAR);

	/**
	 * The parameter <code>public.dropoverviewconstraints.ovcolumn</code>.
	 */
	public static final org.jooq.Parameter<java.lang.String> OVCOLUMN = createParameter("ovcolumn", org.jooq.impl.SQLDataType.VARCHAR);

	/**
	 * Create a new routine call instance
	 */
	public Dropoverviewconstraints1() {
		super("dropoverviewconstraints", us.fok.lenzenslijper.models.jooq.Public.PUBLIC, org.jooq.impl.SQLDataType.BOOLEAN);

		setReturnParameter(RETURN_VALUE);
		addInParameter(OVSCHEMA);
		addInParameter(OVTABLE);
		addInParameter(OVCOLUMN);
		setOverloaded(true);
	}

	/**
	 * Set the <code>ovschema</code> parameter IN value to the routine
	 */
	public void setOvschema(java.lang.String value) {
		setValue(us.fok.lenzenslijper.models.jooq.routines.Dropoverviewconstraints1.OVSCHEMA, value);
	}

	/**
	 * Set the <code>ovschema</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public void setOvschema(org.jooq.Field<java.lang.String> field) {
		setField(OVSCHEMA, field);
	}

	/**
	 * Set the <code>ovtable</code> parameter IN value to the routine
	 */
	public void setOvtable(java.lang.String value) {
		setValue(us.fok.lenzenslijper.models.jooq.routines.Dropoverviewconstraints1.OVTABLE, value);
	}

	/**
	 * Set the <code>ovtable</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public void setOvtable(org.jooq.Field<java.lang.String> field) {
		setField(OVTABLE, field);
	}

	/**
	 * Set the <code>ovcolumn</code> parameter IN value to the routine
	 */
	public void setOvcolumn(java.lang.String value) {
		setValue(us.fok.lenzenslijper.models.jooq.routines.Dropoverviewconstraints1.OVCOLUMN, value);
	}

	/**
	 * Set the <code>ovcolumn</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public void setOvcolumn(org.jooq.Field<java.lang.String> field) {
		setField(OVCOLUMN, field);
	}
}
