/**
 * This class is generated by jOOQ
 */
package us.fok.lenzenslijper.models.jooq.routines;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PostgisTypeName extends org.jooq.impl.AbstractRoutine<java.lang.String> {

	private static final long serialVersionUID = -777917665;

	/**
	 * The parameter <code>public.postgis_type_name.RETURN_VALUE</code>.
	 */
	public static final org.jooq.Parameter<java.lang.String> RETURN_VALUE = createParameter("RETURN_VALUE", org.jooq.impl.SQLDataType.VARCHAR);

	/**
	 * The parameter <code>public.postgis_type_name.geomname</code>.
	 */
	public static final org.jooq.Parameter<java.lang.String> GEOMNAME = createParameter("geomname", org.jooq.impl.SQLDataType.VARCHAR);

	/**
	 * The parameter <code>public.postgis_type_name.coord_dimension</code>.
	 */
	public static final org.jooq.Parameter<java.lang.Integer> COORD_DIMENSION = createParameter("coord_dimension", org.jooq.impl.SQLDataType.INTEGER);

	/**
	 * The parameter <code>public.postgis_type_name.use_new_name</code>.
	 */
	public static final org.jooq.Parameter<java.lang.Boolean> USE_NEW_NAME = createParameter("use_new_name", org.jooq.impl.SQLDataType.BOOLEAN);

	/**
	 * Create a new routine call instance
	 */
	public PostgisTypeName() {
		super("postgis_type_name", us.fok.lenzenslijper.models.jooq.Public.PUBLIC, org.jooq.impl.SQLDataType.VARCHAR);

		setReturnParameter(RETURN_VALUE);
		addInParameter(GEOMNAME);
		addInParameter(COORD_DIMENSION);
		addInParameter(USE_NEW_NAME);
	}

	/**
	 * Set the <code>geomname</code> parameter IN value to the routine
	 */
	public void setGeomname(java.lang.String value) {
		setValue(us.fok.lenzenslijper.models.jooq.routines.PostgisTypeName.GEOMNAME, value);
	}

	/**
	 * Set the <code>geomname</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public void setGeomname(org.jooq.Field<java.lang.String> field) {
		setField(GEOMNAME, field);
	}

	/**
	 * Set the <code>coord_dimension</code> parameter IN value to the routine
	 */
	public void setCoordDimension(java.lang.Integer value) {
		setValue(us.fok.lenzenslijper.models.jooq.routines.PostgisTypeName.COORD_DIMENSION, value);
	}

	/**
	 * Set the <code>coord_dimension</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public void setCoordDimension(org.jooq.Field<java.lang.Integer> field) {
		setField(COORD_DIMENSION, field);
	}

	/**
	 * Set the <code>use_new_name</code> parameter IN value to the routine
	 */
	public void setUseNewName(java.lang.Boolean value) {
		setValue(us.fok.lenzenslijper.models.jooq.routines.PostgisTypeName.USE_NEW_NAME, value);
	}

	/**
	 * Set the <code>use_new_name</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public void setUseNewName(org.jooq.Field<java.lang.Boolean> field) {
		setField(USE_NEW_NAME, field);
	}
}
