/**
 * This class is generated by jOOQ
 */
package us.fok.lenzenslijper.models.jooq.routines;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProcessDocumentPreRelease extends org.jooq.impl.AbstractRoutine<java.lang.Void> {

	private static final long serialVersionUID = -2103806335;

	/**
	 * The parameter <code>public.process_document_pre_release._release_tag_id</code>.
	 */
	public static final org.jooq.Parameter<java.lang.Object> _RELEASE_TAG_ID = createParameter("_release_tag_id", org.jooq.impl.DefaultDataType.getDefaultDataType("USER-DEFINED"));

	/**
	 * The parameter <code>public.process_document_pre_release._document_id</code>.
	 */
	public static final org.jooq.Parameter<java.util.UUID> _DOCUMENT_ID = createParameter("_document_id", org.jooq.impl.SQLDataType.UUID);

	/**
	 * Create a new routine call instance
	 */
	public ProcessDocumentPreRelease() {
		super("process_document_pre_release", us.fok.lenzenslijper.models.jooq.Public.PUBLIC);

		addInParameter(_RELEASE_TAG_ID);
		addInParameter(_DOCUMENT_ID);
	}

	/**
	 * Set the <code>_release_tag_id</code> parameter IN value to the routine
	 */
	public void set_ReleaseTagId(java.lang.Object value) {
		setValue(us.fok.lenzenslijper.models.jooq.routines.ProcessDocumentPreRelease._RELEASE_TAG_ID, value);
	}

	/**
	 * Set the <code>_document_id</code> parameter IN value to the routine
	 */
	public void set_DocumentId(java.util.UUID value) {
		setValue(us.fok.lenzenslijper.models.jooq.routines.ProcessDocumentPreRelease._DOCUMENT_ID, value);
	}
}
