/**
 * This class is generated by jOOQ
 */
package us.fok.lenzenslijper.models.jooq.routines;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RecursivelyNarrowedConcepts extends org.jooq.impl.AbstractRoutine<java.lang.Void> {

	private static final long serialVersionUID = 1184559792;

	/**
	 * The parameter <code>public.recursively_narrowed_concepts.top_concept_id</code>.
	 */
	public static final org.jooq.Parameter<java.util.UUID> TOP_CONCEPT_ID = createParameter("top_concept_id", org.jooq.impl.SQLDataType.UUID);

	/**
	 * The parameter <code>public.recursively_narrowed_concepts.concept_id</code>.
	 */
	public static final org.jooq.Parameter<java.util.UUID> CONCEPT_ID = createParameter("concept_id", org.jooq.impl.SQLDataType.UUID);

	/**
	 * The parameter <code>public.recursively_narrowed_concepts.parent_concept_id</code>.
	 */
	public static final org.jooq.Parameter<java.util.UUID> PARENT_CONCEPT_ID = createParameter("parent_concept_id", org.jooq.impl.SQLDataType.UUID);

	/**
	 * The parameter <code>public.recursively_narrowed_concepts.project_id</code>.
	 */
	public static final org.jooq.Parameter<java.util.UUID> PROJECT_ID = createParameter("project_id", org.jooq.impl.SQLDataType.UUID);

	/**
	 * The parameter <code>public.recursively_narrowed_concepts.name</code>.
	 */
	public static final org.jooq.Parameter<java.lang.Object> NAME = createParameter("name", org.jooq.impl.DefaultDataType.getDefaultDataType("USER-DEFINED"));

	/**
	 * The parameter <code>public.recursively_narrowed_concepts.short_name</code>.
	 */
	public static final org.jooq.Parameter<java.lang.Object> SHORT_NAME = createParameter("short_name", org.jooq.impl.DefaultDataType.getDefaultDataType("USER-DEFINED"));

	/**
	 * The parameter <code>public.recursively_narrowed_concepts.slug</code>.
	 */
	public static final org.jooq.Parameter<java.lang.Object> SLUG = createParameter("slug", org.jooq.impl.DefaultDataType.getDefaultDataType("USER-DEFINED"));

	/**
	 * Create a new routine call instance
	 */
	public RecursivelyNarrowedConcepts() {
		super("recursively_narrowed_concepts", us.fok.lenzenslijper.models.jooq.Public.PUBLIC);

		addInParameter(TOP_CONCEPT_ID);
		addOutParameter(CONCEPT_ID);
		addOutParameter(PARENT_CONCEPT_ID);
		addOutParameter(PROJECT_ID);
		addOutParameter(NAME);
		addOutParameter(SHORT_NAME);
		addOutParameter(SLUG);
	}

	/**
	 * Set the <code>top_concept_id</code> parameter IN value to the routine
	 */
	public void setTopConceptId(java.util.UUID value) {
		setValue(us.fok.lenzenslijper.models.jooq.routines.RecursivelyNarrowedConcepts.TOP_CONCEPT_ID, value);
	}

	/**
	 * Get the <code>concept_id</code> parameter OUT value from the routine
	 */
	public java.util.UUID getConceptId() {
		return getValue(CONCEPT_ID);
	}

	/**
	 * Get the <code>parent_concept_id</code> parameter OUT value from the routine
	 */
	public java.util.UUID getParentConceptId() {
		return getValue(PARENT_CONCEPT_ID);
	}

	/**
	 * Get the <code>project_id</code> parameter OUT value from the routine
	 */
	public java.util.UUID getProjectId() {
		return getValue(PROJECT_ID);
	}

	/**
	 * Get the <code>name</code> parameter OUT value from the routine
	 */
	public java.lang.Object getName_() {
		return getValue(NAME);
	}

	/**
	 * Get the <code>short_name</code> parameter OUT value from the routine
	 */
	public java.lang.Object getShortName() {
		return getValue(SHORT_NAME);
	}

	/**
	 * Get the <code>slug</code> parameter OUT value from the routine
	 */
	public java.lang.Object getSlug() {
		return getValue(SLUG);
	}
}
