/**
 * This class is generated by jOOQ
 */
package us.fok.lenzenslijper.models.jooq.udt.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GeomvalRecord extends org.jooq.impl.UDTRecordImpl<us.fok.lenzenslijper.models.jooq.udt.records.GeomvalRecord> {

	private static final long serialVersionUID = 1729447496;


	/**
	 * Setter for <code>public.geomval.geom</code>.
	 */
	public void setGeom(java.lang.Object value) {
		setValue(us.fok.lenzenslijper.models.jooq.udt.Geomval.GEOM, value);
	}

	/**
	 * Getter for <code>public.geomval.geom</code>.
	 */
	public java.lang.Object getGeom() {
		return getValue(us.fok.lenzenslijper.models.jooq.udt.Geomval.GEOM);
	}

	/**
	 * Setter for <code>public.geomval.val</code>.
	 */
	public void setVal(java.lang.Double value) {
		setValue(us.fok.lenzenslijper.models.jooq.udt.Geomval.VAL, value);
	}

	/**
	 * Getter for <code>public.geomval.val</code>.
	 */
	public java.lang.Double getVal() {
		return getValue(us.fok.lenzenslijper.models.jooq.udt.Geomval.VAL);
	}

	/**
	 * Create a new <code>public.geomval</code> record
	 */
	public GeomvalRecord() {
		super(us.fok.lenzenslijper.models.jooq.udt.Geomval.GEOMVAL);
	}
}
