/**
 * This class is generated by jOOQ
 */
package us.fok.lenzenslijper.models.jooq.udt.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ReclassargRecord extends org.jooq.impl.UDTRecordImpl<us.fok.lenzenslijper.models.jooq.udt.records.ReclassargRecord> {

	private static final long serialVersionUID = 887108462;


	/**
	 * Setter for <code>public.reclassarg.nband</code>.
	 */
	public void setNband(java.lang.Integer value) {
		setValue(us.fok.lenzenslijper.models.jooq.udt.Reclassarg.NBAND, value);
	}

	/**
	 * Getter for <code>public.reclassarg.nband</code>.
	 */
	public java.lang.Integer getNband() {
		return getValue(us.fok.lenzenslijper.models.jooq.udt.Reclassarg.NBAND);
	}

	/**
	 * Setter for <code>public.reclassarg.reclassexpr</code>.
	 */
	public void setReclassexpr(java.lang.String value) {
		setValue(us.fok.lenzenslijper.models.jooq.udt.Reclassarg.RECLASSEXPR, value);
	}

	/**
	 * Getter for <code>public.reclassarg.reclassexpr</code>.
	 */
	public java.lang.String getReclassexpr() {
		return getValue(us.fok.lenzenslijper.models.jooq.udt.Reclassarg.RECLASSEXPR);
	}

	/**
	 * Setter for <code>public.reclassarg.pixeltype</code>.
	 */
	public void setPixeltype(java.lang.String value) {
		setValue(us.fok.lenzenslijper.models.jooq.udt.Reclassarg.PIXELTYPE, value);
	}

	/**
	 * Getter for <code>public.reclassarg.pixeltype</code>.
	 */
	public java.lang.String getPixeltype() {
		return getValue(us.fok.lenzenslijper.models.jooq.udt.Reclassarg.PIXELTYPE);
	}

	/**
	 * Setter for <code>public.reclassarg.nodataval</code>.
	 */
	public void setNodataval(java.lang.Double value) {
		setValue(us.fok.lenzenslijper.models.jooq.udt.Reclassarg.NODATAVAL, value);
	}

	/**
	 * Getter for <code>public.reclassarg.nodataval</code>.
	 */
	public java.lang.Double getNodataval() {
		return getValue(us.fok.lenzenslijper.models.jooq.udt.Reclassarg.NODATAVAL);
	}

	/**
	 * Create a new <code>public.reclassarg</code> record
	 */
	public ReclassargRecord() {
		super(us.fok.lenzenslijper.models.jooq.udt.Reclassarg.RECLASSARG);
	}
}
