/**
 * This class is generated by jOOQ
 */
package us.fok.lenzenslijper.models.jooq.udt.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RevisionSummaryRecord extends org.jooq.impl.UDTRecordImpl<us.fok.lenzenslijper.models.jooq.udt.records.RevisionSummaryRecord> {

	private static final long serialVersionUID = -1957619340;


	/**
	 * Setter for <code>public.revision_summary.revision_id</code>.
	 */
	public void setRevisionId(java.util.UUID value) {
		setValue(us.fok.lenzenslijper.models.jooq.udt.RevisionSummary.REVISION_ID, value);
	}

	/**
	 * Getter for <code>public.revision_summary.revision_id</code>.
	 */
	public java.util.UUID getRevisionId() {
		return getValue(us.fok.lenzenslijper.models.jooq.udt.RevisionSummary.REVISION_ID);
	}

	/**
	 * Setter for <code>public.revision_summary.document_id</code>.
	 */
	public void setDocumentId(java.util.UUID value) {
		setValue(us.fok.lenzenslijper.models.jooq.udt.RevisionSummary.DOCUMENT_ID, value);
	}

	/**
	 * Getter for <code>public.revision_summary.document_id</code>.
	 */
	public java.util.UUID getDocumentId() {
		return getValue(us.fok.lenzenslijper.models.jooq.udt.RevisionSummary.DOCUMENT_ID);
	}

	/**
	 * Setter for <code>public.revision_summary.created</code>.
	 */
	public void setCreated(java.lang.Object value) {
		setValue(us.fok.lenzenslijper.models.jooq.udt.RevisionSummary.CREATED, value);
	}

	/**
	 * Getter for <code>public.revision_summary.created</code>.
	 */
	public java.lang.Object getCreated() {
		return getValue(us.fok.lenzenslijper.models.jooq.udt.RevisionSummary.CREATED);
	}

	/**
	 * Setter for <code>public.revision_summary.user_id</code>.
	 */
	public void setUserId(java.util.UUID value) {
		setValue(us.fok.lenzenslijper.models.jooq.udt.RevisionSummary.USER_ID, value);
	}

	/**
	 * Getter for <code>public.revision_summary.user_id</code>.
	 */
	public java.util.UUID getUserId() {
		return getValue(us.fok.lenzenslijper.models.jooq.udt.RevisionSummary.USER_ID);
	}

	/**
	 * Setter for <code>public.revision_summary.document_type_id</code>.
	 */
	public void setDocumentTypeId(java.lang.Object value) {
		setValue(us.fok.lenzenslijper.models.jooq.udt.RevisionSummary.DOCUMENT_TYPE_ID, value);
	}

	/**
	 * Getter for <code>public.revision_summary.document_type_id</code>.
	 */
	public java.lang.Object getDocumentTypeId() {
		return getValue(us.fok.lenzenslijper.models.jooq.udt.RevisionSummary.DOCUMENT_TYPE_ID);
	}

	/**
	 * Setter for <code>public.revision_summary.project_id</code>.
	 */
	public void setProjectId(java.util.UUID value) {
		setValue(us.fok.lenzenslijper.models.jooq.udt.RevisionSummary.PROJECT_ID, value);
	}

	/**
	 * Getter for <code>public.revision_summary.project_id</code>.
	 */
	public java.util.UUID getProjectId() {
		return getValue(us.fok.lenzenslijper.models.jooq.udt.RevisionSummary.PROJECT_ID);
	}

	/**
	 * Create a new <code>public.revision_summary</code> record
	 */
	public RevisionSummaryRecord() {
		super(us.fok.lenzenslijper.models.jooq.udt.RevisionSummary.REVISION_SUMMARY);
	}
}
