/**
 * This class is generated by jOOQ
 */
package us.fok.lenzenslijper.models.jooq.udt.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UnionargRecord extends org.jooq.impl.UDTRecordImpl<us.fok.lenzenslijper.models.jooq.udt.records.UnionargRecord> {

	private static final long serialVersionUID = -1448086976;


	/**
	 * Setter for <code>public.unionarg.nband</code>.
	 */
	public void setNband(java.lang.Integer value) {
		setValue(us.fok.lenzenslijper.models.jooq.udt.Unionarg.NBAND, value);
	}

	/**
	 * Getter for <code>public.unionarg.nband</code>.
	 */
	public java.lang.Integer getNband() {
		return getValue(us.fok.lenzenslijper.models.jooq.udt.Unionarg.NBAND);
	}

	/**
	 * Setter for <code>public.unionarg.uniontype</code>.
	 */
	public void setUniontype(java.lang.String value) {
		setValue(us.fok.lenzenslijper.models.jooq.udt.Unionarg.UNIONTYPE, value);
	}

	/**
	 * Getter for <code>public.unionarg.uniontype</code>.
	 */
	public java.lang.String getUniontype() {
		return getValue(us.fok.lenzenslijper.models.jooq.udt.Unionarg.UNIONTYPE);
	}

	/**
	 * Create a new <code>public.unionarg</code> record
	 */
	public UnionargRecord() {
		super(us.fok.lenzenslijper.models.jooq.udt.Unionarg.UNIONARG);
	}
}
