/**
 * This class is generated by jOOQ
 */
package us.fok.lenzenslijper.models.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AssessmentTypes extends org.jooq.impl.TableImpl<us.fok.lenzenslijper.models.jooq.tables.records.AssessmentTypesRecord> {

	private static final long serialVersionUID = 1747829100;

	/**
	 * The singleton instance of <code>public.assessment_types</code>
	 */
	public static final us.fok.lenzenslijper.models.jooq.tables.AssessmentTypes ASSESSMENT_TYPES = new us.fok.lenzenslijper.models.jooq.tables.AssessmentTypes();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<us.fok.lenzenslijper.models.jooq.tables.records.AssessmentTypesRecord> getRecordType() {
		return us.fok.lenzenslijper.models.jooq.tables.records.AssessmentTypesRecord.class;
	}

	/**
	 * The column <code>public.assessment_types.assessment_type_id</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.AssessmentTypesRecord, java.lang.Integer> ASSESSMENT_TYPE_ID = createField("assessment_type_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.assessment_types.slug</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.AssessmentTypesRecord, java.lang.String> SLUG = createField("slug", org.jooq.impl.SQLDataType.CLOB.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.assessment_types.row_created</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.AssessmentTypesRecord, java.sql.Timestamp> ROW_CREATED = createField("row_created", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.assessment_types.row_updated</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.AssessmentTypesRecord, java.sql.Timestamp> ROW_UPDATED = createField("row_updated", org.jooq.impl.SQLDataType.TIMESTAMP.defaulted(true), this, "");

	/**
	 * Create a <code>public.assessment_types</code> table reference
	 */
	public AssessmentTypes() {
		this("assessment_types", null);
	}

	/**
	 * Create an aliased <code>public.assessment_types</code> table reference
	 */
	public AssessmentTypes(java.lang.String alias) {
		this(alias, us.fok.lenzenslijper.models.jooq.tables.AssessmentTypes.ASSESSMENT_TYPES);
	}

	private AssessmentTypes(java.lang.String alias, org.jooq.Table<us.fok.lenzenslijper.models.jooq.tables.records.AssessmentTypesRecord> aliased) {
		this(alias, aliased, null);
	}

	private AssessmentTypes(java.lang.String alias, org.jooq.Table<us.fok.lenzenslijper.models.jooq.tables.records.AssessmentTypesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, us.fok.lenzenslijper.models.jooq.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<us.fok.lenzenslijper.models.jooq.tables.records.AssessmentTypesRecord, java.lang.Integer> getIdentity() {
		return us.fok.lenzenslijper.models.jooq.Keys.IDENTITY_ASSESSMENT_TYPES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<us.fok.lenzenslijper.models.jooq.tables.records.AssessmentTypesRecord> getPrimaryKey() {
		return us.fok.lenzenslijper.models.jooq.Keys.UNIQ_ASSESSMENT_TYPES_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<us.fok.lenzenslijper.models.jooq.tables.records.AssessmentTypesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<us.fok.lenzenslijper.models.jooq.tables.records.AssessmentTypesRecord>>asList(us.fok.lenzenslijper.models.jooq.Keys.UNIQ_ASSESSMENT_TYPES_ID, us.fok.lenzenslijper.models.jooq.Keys.UNIQ_ASSESSMENT_TYPES_SLUG);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public us.fok.lenzenslijper.models.jooq.tables.AssessmentTypes as(java.lang.String alias) {
		return new us.fok.lenzenslijper.models.jooq.tables.AssessmentTypes(alias, this);
	}

	/**
	 * Rename this table
	 */
	public us.fok.lenzenslijper.models.jooq.tables.AssessmentTypes rename(java.lang.String name) {
		return new us.fok.lenzenslijper.models.jooq.tables.AssessmentTypes(name, null);
	}
}
