/**
 * This class is generated by jOOQ
 */
package us.fok.lenzenslijper.models.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Assets extends org.jooq.impl.TableImpl<us.fok.lenzenslijper.models.jooq.tables.records.AssetsRecord> {

	private static final long serialVersionUID = -933208663;

	/**
	 * The singleton instance of <code>public.assets</code>
	 */
	public static final us.fok.lenzenslijper.models.jooq.tables.Assets ASSETS = new us.fok.lenzenslijper.models.jooq.tables.Assets();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<us.fok.lenzenslijper.models.jooq.tables.records.AssetsRecord> getRecordType() {
		return us.fok.lenzenslijper.models.jooq.tables.records.AssetsRecord.class;
	}

	/**
	 * The column <code>public.assets.asset_id</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.AssetsRecord, java.util.UUID> ASSET_ID = createField("asset_id", org.jooq.impl.SQLDataType.UUID.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.assets.asset_type_id</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.AssetsRecord, java.lang.Integer> ASSET_TYPE_ID = createField("asset_type_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.assets.digest</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.AssetsRecord, java.lang.String> DIGEST = createField("digest", org.jooq.impl.SQLDataType.CLOB.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.assets.content</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.AssetsRecord, byte[]> CONTENT = createField("content", org.jooq.impl.SQLDataType.BLOB.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.assets.row_created</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.AssetsRecord, java.sql.Timestamp> ROW_CREATED = createField("row_created", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.assets.row_updated</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.AssetsRecord, java.sql.Timestamp> ROW_UPDATED = createField("row_updated", org.jooq.impl.SQLDataType.TIMESTAMP.defaulted(true), this, "");

	/**
	 * Create a <code>public.assets</code> table reference
	 */
	public Assets() {
		this("assets", null);
	}

	/**
	 * Create an aliased <code>public.assets</code> table reference
	 */
	public Assets(java.lang.String alias) {
		this(alias, us.fok.lenzenslijper.models.jooq.tables.Assets.ASSETS);
	}

	private Assets(java.lang.String alias, org.jooq.Table<us.fok.lenzenslijper.models.jooq.tables.records.AssetsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Assets(java.lang.String alias, org.jooq.Table<us.fok.lenzenslijper.models.jooq.tables.records.AssetsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, us.fok.lenzenslijper.models.jooq.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<us.fok.lenzenslijper.models.jooq.tables.records.AssetsRecord> getPrimaryKey() {
		return us.fok.lenzenslijper.models.jooq.Keys.UNIQ_ASSETS_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<us.fok.lenzenslijper.models.jooq.tables.records.AssetsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<us.fok.lenzenslijper.models.jooq.tables.records.AssetsRecord>>asList(us.fok.lenzenslijper.models.jooq.Keys.UNIQ_ASSETS_ID, us.fok.lenzenslijper.models.jooq.Keys.UNIQ_ASSETS_TYPE_DIGEST);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<us.fok.lenzenslijper.models.jooq.tables.records.AssetsRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<us.fok.lenzenslijper.models.jooq.tables.records.AssetsRecord, ?>>asList(us.fok.lenzenslijper.models.jooq.Keys.ASSETS__FOR_ASSETS_TYPE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public us.fok.lenzenslijper.models.jooq.tables.Assets as(java.lang.String alias) {
		return new us.fok.lenzenslijper.models.jooq.tables.Assets(alias, this);
	}

	/**
	 * Rename this table
	 */
	public us.fok.lenzenslijper.models.jooq.tables.Assets rename(java.lang.String name) {
		return new us.fok.lenzenslijper.models.jooq.tables.Assets(name, null);
	}
}
