/**
 * This class is generated by jOOQ
 */
package us.fok.lenzenslijper.models.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ConceptSets extends org.jooq.impl.TableImpl<us.fok.lenzenslijper.models.jooq.tables.records.ConceptSetsRecord> {

	private static final long serialVersionUID = 986688070;

	/**
	 * The singleton instance of <code>public.concept_sets</code>
	 */
	public static final us.fok.lenzenslijper.models.jooq.tables.ConceptSets CONCEPT_SETS = new us.fok.lenzenslijper.models.jooq.tables.ConceptSets();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<us.fok.lenzenslijper.models.jooq.tables.records.ConceptSetsRecord> getRecordType() {
		return us.fok.lenzenslijper.models.jooq.tables.records.ConceptSetsRecord.class;
	}

	/**
	 * The column <code>public.concept_sets.concept_set_id</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.ConceptSetsRecord, java.util.UUID> CONCEPT_SET_ID = createField("concept_set_id", org.jooq.impl.SQLDataType.UUID.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.concept_sets.project_id</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.ConceptSetsRecord, java.util.UUID> PROJECT_ID = createField("project_id", org.jooq.impl.SQLDataType.UUID.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.concept_sets.name</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.ConceptSetsRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.CLOB.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.concept_sets.short_name</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.ConceptSetsRecord, java.lang.String> SHORT_NAME = createField("short_name", org.jooq.impl.SQLDataType.CLOB.defaulted(true), this, "");

	/**
	 * The column <code>public.concept_sets.creator_user_id</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.ConceptSetsRecord, java.util.UUID> CREATOR_USER_ID = createField("creator_user_id", org.jooq.impl.SQLDataType.UUID.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.concept_sets.created</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.ConceptSetsRecord, java.sql.Timestamp> CREATED = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.concept_sets.updater_user_id</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.ConceptSetsRecord, java.util.UUID> UPDATER_USER_ID = createField("updater_user_id", org.jooq.impl.SQLDataType.UUID.defaulted(true), this, "");

	/**
	 * The column <code>public.concept_sets.updated</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.ConceptSetsRecord, java.sql.Timestamp> UPDATED = createField("updated", org.jooq.impl.SQLDataType.TIMESTAMP.defaulted(true), this, "");

	/**
	 * The column <code>public.concept_sets.row_created</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.ConceptSetsRecord, java.sql.Timestamp> ROW_CREATED = createField("row_created", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.concept_sets.row_updated</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.ConceptSetsRecord, java.sql.Timestamp> ROW_UPDATED = createField("row_updated", org.jooq.impl.SQLDataType.TIMESTAMP.defaulted(true), this, "");

	/**
	 * Create a <code>public.concept_sets</code> table reference
	 */
	public ConceptSets() {
		this("concept_sets", null);
	}

	/**
	 * Create an aliased <code>public.concept_sets</code> table reference
	 */
	public ConceptSets(java.lang.String alias) {
		this(alias, us.fok.lenzenslijper.models.jooq.tables.ConceptSets.CONCEPT_SETS);
	}

	private ConceptSets(java.lang.String alias, org.jooq.Table<us.fok.lenzenslijper.models.jooq.tables.records.ConceptSetsRecord> aliased) {
		this(alias, aliased, null);
	}

	private ConceptSets(java.lang.String alias, org.jooq.Table<us.fok.lenzenslijper.models.jooq.tables.records.ConceptSetsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, us.fok.lenzenslijper.models.jooq.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<us.fok.lenzenslijper.models.jooq.tables.records.ConceptSetsRecord> getPrimaryKey() {
		return us.fok.lenzenslijper.models.jooq.Keys.UNIQ_CON_SETS_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<us.fok.lenzenslijper.models.jooq.tables.records.ConceptSetsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<us.fok.lenzenslijper.models.jooq.tables.records.ConceptSetsRecord>>asList(us.fok.lenzenslijper.models.jooq.Keys.UNIQ_CON_SETS_ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<us.fok.lenzenslijper.models.jooq.tables.records.ConceptSetsRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<us.fok.lenzenslijper.models.jooq.tables.records.ConceptSetsRecord, ?>>asList(us.fok.lenzenslijper.models.jooq.Keys.CONCEPT_SETS__FOR_CON_SETS_PROJECT, us.fok.lenzenslijper.models.jooq.Keys.CONCEPT_SETS__FOR_CON_SETS_CREATOR, us.fok.lenzenslijper.models.jooq.Keys.CONCEPT_SETS__FOR_CON_SETS_UPDATER);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public us.fok.lenzenslijper.models.jooq.tables.ConceptSets as(java.lang.String alias) {
		return new us.fok.lenzenslijper.models.jooq.tables.ConceptSets(alias, this);
	}

	/**
	 * Rename this table
	 */
	public us.fok.lenzenslijper.models.jooq.tables.ConceptSets rename(java.lang.String name) {
		return new us.fok.lenzenslijper.models.jooq.tables.ConceptSets(name, null);
	}
}
