/**
 * This class is generated by jOOQ
 */
package us.fok.lenzenslijper.models.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DocumentTypes extends org.jooq.impl.TableImpl<us.fok.lenzenslijper.models.jooq.tables.records.DocumentTypesRecord> {

	private static final long serialVersionUID = -805029400;

	/**
	 * The singleton instance of <code>public.document_types</code>
	 */
	public static final us.fok.lenzenslijper.models.jooq.tables.DocumentTypes DOCUMENT_TYPES = new us.fok.lenzenslijper.models.jooq.tables.DocumentTypes();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<us.fok.lenzenslijper.models.jooq.tables.records.DocumentTypesRecord> getRecordType() {
		return us.fok.lenzenslijper.models.jooq.tables.records.DocumentTypesRecord.class;
	}

	/**
	 * The column <code>public.document_types.document_type_id</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.DocumentTypesRecord, java.lang.Integer> DOCUMENT_TYPE_ID = createField("document_type_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.document_types.slug</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.DocumentTypesRecord, java.lang.String> SLUG = createField("slug", org.jooq.impl.SQLDataType.CLOB.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.document_types.row_created</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.DocumentTypesRecord, java.sql.Timestamp> ROW_CREATED = createField("row_created", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.document_types.row_updated</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.DocumentTypesRecord, java.sql.Timestamp> ROW_UPDATED = createField("row_updated", org.jooq.impl.SQLDataType.TIMESTAMP.defaulted(true), this, "");

	/**
	 * Create a <code>public.document_types</code> table reference
	 */
	public DocumentTypes() {
		this("document_types", null);
	}

	/**
	 * Create an aliased <code>public.document_types</code> table reference
	 */
	public DocumentTypes(java.lang.String alias) {
		this(alias, us.fok.lenzenslijper.models.jooq.tables.DocumentTypes.DOCUMENT_TYPES);
	}

	private DocumentTypes(java.lang.String alias, org.jooq.Table<us.fok.lenzenslijper.models.jooq.tables.records.DocumentTypesRecord> aliased) {
		this(alias, aliased, null);
	}

	private DocumentTypes(java.lang.String alias, org.jooq.Table<us.fok.lenzenslijper.models.jooq.tables.records.DocumentTypesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, us.fok.lenzenslijper.models.jooq.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<us.fok.lenzenslijper.models.jooq.tables.records.DocumentTypesRecord, java.lang.Integer> getIdentity() {
		return us.fok.lenzenslijper.models.jooq.Keys.IDENTITY_DOCUMENT_TYPES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<us.fok.lenzenslijper.models.jooq.tables.records.DocumentTypesRecord> getPrimaryKey() {
		return us.fok.lenzenslijper.models.jooq.Keys.UNIQ_DOCUMENT_TYPES_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<us.fok.lenzenslijper.models.jooq.tables.records.DocumentTypesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<us.fok.lenzenslijper.models.jooq.tables.records.DocumentTypesRecord>>asList(us.fok.lenzenslijper.models.jooq.Keys.UNIQ_DOCUMENT_TYPES_ID, us.fok.lenzenslijper.models.jooq.Keys.UNIQ_DOCUMENT_TYPES_SLUG);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public us.fok.lenzenslijper.models.jooq.tables.DocumentTypes as(java.lang.String alias) {
		return new us.fok.lenzenslijper.models.jooq.tables.DocumentTypes(alias, this);
	}

	/**
	 * Rename this table
	 */
	public us.fok.lenzenslijper.models.jooq.tables.DocumentTypes rename(java.lang.String name) {
		return new us.fok.lenzenslijper.models.jooq.tables.DocumentTypes(name, null);
	}
}
