/**
 * This class is generated by jOOQ
 */
package us.fok.lenzenslijper.models.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Entities extends org.jooq.impl.TableImpl<us.fok.lenzenslijper.models.jooq.tables.records.EntitiesRecord> {

	private static final long serialVersionUID = -225515096;

	/**
	 * The singleton instance of <code>public.entities</code>
	 */
	public static final us.fok.lenzenslijper.models.jooq.tables.Entities ENTITIES = new us.fok.lenzenslijper.models.jooq.tables.Entities();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<us.fok.lenzenslijper.models.jooq.tables.records.EntitiesRecord> getRecordType() {
		return us.fok.lenzenslijper.models.jooq.tables.records.EntitiesRecord.class;
	}

	/**
	 * The column <code>public.entities.entity_id</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.EntitiesRecord, java.util.UUID> ENTITY_ID = createField("entity_id", org.jooq.impl.SQLDataType.UUID.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.entities.row_created</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.EntitiesRecord, java.sql.Timestamp> ROW_CREATED = createField("row_created", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>public.entities</code> table reference
	 */
	public Entities() {
		this("entities", null);
	}

	/**
	 * Create an aliased <code>public.entities</code> table reference
	 */
	public Entities(java.lang.String alias) {
		this(alias, us.fok.lenzenslijper.models.jooq.tables.Entities.ENTITIES);
	}

	private Entities(java.lang.String alias, org.jooq.Table<us.fok.lenzenslijper.models.jooq.tables.records.EntitiesRecord> aliased) {
		this(alias, aliased, null);
	}

	private Entities(java.lang.String alias, org.jooq.Table<us.fok.lenzenslijper.models.jooq.tables.records.EntitiesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, us.fok.lenzenslijper.models.jooq.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<us.fok.lenzenslijper.models.jooq.tables.records.EntitiesRecord> getPrimaryKey() {
		return us.fok.lenzenslijper.models.jooq.Keys.UNIQ_ENTITIES_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<us.fok.lenzenslijper.models.jooq.tables.records.EntitiesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<us.fok.lenzenslijper.models.jooq.tables.records.EntitiesRecord>>asList(us.fok.lenzenslijper.models.jooq.Keys.UNIQ_ENTITIES_ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public us.fok.lenzenslijper.models.jooq.tables.Entities as(java.lang.String alias) {
		return new us.fok.lenzenslijper.models.jooq.tables.Entities(alias, this);
	}

	/**
	 * Rename this table
	 */
	public us.fok.lenzenslijper.models.jooq.tables.Entities rename(java.lang.String name) {
		return new us.fok.lenzenslijper.models.jooq.tables.Entities(name, null);
	}
}
