/**
 * This class is generated by jOOQ
 */
package us.fok.lenzenslijper.models.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GeographyColumns extends org.jooq.impl.TableImpl<us.fok.lenzenslijper.models.jooq.tables.records.GeographyColumnsRecord> {

	private static final long serialVersionUID = 1797915085;

	/**
	 * The singleton instance of <code>public.geography_columns</code>
	 */
	public static final us.fok.lenzenslijper.models.jooq.tables.GeographyColumns GEOGRAPHY_COLUMNS = new us.fok.lenzenslijper.models.jooq.tables.GeographyColumns();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<us.fok.lenzenslijper.models.jooq.tables.records.GeographyColumnsRecord> getRecordType() {
		return us.fok.lenzenslijper.models.jooq.tables.records.GeographyColumnsRecord.class;
	}

	/**
	 * The column <code>public.geography_columns.f_table_catalog</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.GeographyColumnsRecord, java.lang.String> F_TABLE_CATALOG = createField("f_table_catalog", org.jooq.impl.SQLDataType.VARCHAR.defaulted(true), this, "");

	/**
	 * The column <code>public.geography_columns.f_table_schema</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.GeographyColumnsRecord, java.lang.String> F_TABLE_SCHEMA = createField("f_table_schema", org.jooq.impl.SQLDataType.VARCHAR.defaulted(true), this, "");

	/**
	 * The column <code>public.geography_columns.f_table_name</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.GeographyColumnsRecord, java.lang.String> F_TABLE_NAME = createField("f_table_name", org.jooq.impl.SQLDataType.VARCHAR.defaulted(true), this, "");

	/**
	 * The column <code>public.geography_columns.f_geography_column</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.GeographyColumnsRecord, java.lang.String> F_GEOGRAPHY_COLUMN = createField("f_geography_column", org.jooq.impl.SQLDataType.VARCHAR.defaulted(true), this, "");

	/**
	 * The column <code>public.geography_columns.coord_dimension</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.GeographyColumnsRecord, java.lang.Integer> COORD_DIMENSION = createField("coord_dimension", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "");

	/**
	 * The column <code>public.geography_columns.srid</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.GeographyColumnsRecord, java.lang.Integer> SRID = createField("srid", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "");

	/**
	 * The column <code>public.geography_columns.type</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.GeographyColumnsRecord, java.lang.String> TYPE = createField("type", org.jooq.impl.SQLDataType.CLOB.defaulted(true), this, "");

	/**
	 * Create a <code>public.geography_columns</code> table reference
	 */
	public GeographyColumns() {
		this("geography_columns", null);
	}

	/**
	 * Create an aliased <code>public.geography_columns</code> table reference
	 */
	public GeographyColumns(java.lang.String alias) {
		this(alias, us.fok.lenzenslijper.models.jooq.tables.GeographyColumns.GEOGRAPHY_COLUMNS);
	}

	private GeographyColumns(java.lang.String alias, org.jooq.Table<us.fok.lenzenslijper.models.jooq.tables.records.GeographyColumnsRecord> aliased) {
		this(alias, aliased, null);
	}

	private GeographyColumns(java.lang.String alias, org.jooq.Table<us.fok.lenzenslijper.models.jooq.tables.records.GeographyColumnsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, us.fok.lenzenslijper.models.jooq.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public us.fok.lenzenslijper.models.jooq.tables.GeographyColumns as(java.lang.String alias) {
		return new us.fok.lenzenslijper.models.jooq.tables.GeographyColumns(alias, this);
	}

	/**
	 * Rename this table
	 */
	public us.fok.lenzenslijper.models.jooq.tables.GeographyColumns rename(java.lang.String name) {
		return new us.fok.lenzenslijper.models.jooq.tables.GeographyColumns(name, null);
	}
}
