/**
 * This class is generated by jOOQ
 */
package us.fok.lenzenslijper.models.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LinkTargetTypes extends org.jooq.impl.TableImpl<us.fok.lenzenslijper.models.jooq.tables.records.LinkTargetTypesRecord> {

	private static final long serialVersionUID = 864267806;

	/**
	 * The singleton instance of <code>public.link_target_types</code>
	 */
	public static final us.fok.lenzenslijper.models.jooq.tables.LinkTargetTypes LINK_TARGET_TYPES = new us.fok.lenzenslijper.models.jooq.tables.LinkTargetTypes();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<us.fok.lenzenslijper.models.jooq.tables.records.LinkTargetTypesRecord> getRecordType() {
		return us.fok.lenzenslijper.models.jooq.tables.records.LinkTargetTypesRecord.class;
	}

	/**
	 * The column <code>public.link_target_types.link_target_type_id</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.LinkTargetTypesRecord, java.lang.Integer> LINK_TARGET_TYPE_ID = createField("link_target_type_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.link_target_types.slug</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.LinkTargetTypesRecord, java.lang.String> SLUG = createField("slug", org.jooq.impl.SQLDataType.CLOB.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.link_target_types.row_created</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.LinkTargetTypesRecord, java.sql.Timestamp> ROW_CREATED = createField("row_created", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.link_target_types.row_updated</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.LinkTargetTypesRecord, java.sql.Timestamp> ROW_UPDATED = createField("row_updated", org.jooq.impl.SQLDataType.TIMESTAMP.defaulted(true), this, "");

	/**
	 * Create a <code>public.link_target_types</code> table reference
	 */
	public LinkTargetTypes() {
		this("link_target_types", null);
	}

	/**
	 * Create an aliased <code>public.link_target_types</code> table reference
	 */
	public LinkTargetTypes(java.lang.String alias) {
		this(alias, us.fok.lenzenslijper.models.jooq.tables.LinkTargetTypes.LINK_TARGET_TYPES);
	}

	private LinkTargetTypes(java.lang.String alias, org.jooq.Table<us.fok.lenzenslijper.models.jooq.tables.records.LinkTargetTypesRecord> aliased) {
		this(alias, aliased, null);
	}

	private LinkTargetTypes(java.lang.String alias, org.jooq.Table<us.fok.lenzenslijper.models.jooq.tables.records.LinkTargetTypesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, us.fok.lenzenslijper.models.jooq.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<us.fok.lenzenslijper.models.jooq.tables.records.LinkTargetTypesRecord, java.lang.Integer> getIdentity() {
		return us.fok.lenzenslijper.models.jooq.Keys.IDENTITY_LINK_TARGET_TYPES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<us.fok.lenzenslijper.models.jooq.tables.records.LinkTargetTypesRecord> getPrimaryKey() {
		return us.fok.lenzenslijper.models.jooq.Keys.UNIQ_TARGET_TYPES_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<us.fok.lenzenslijper.models.jooq.tables.records.LinkTargetTypesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<us.fok.lenzenslijper.models.jooq.tables.records.LinkTargetTypesRecord>>asList(us.fok.lenzenslijper.models.jooq.Keys.UNIQ_TARGET_TYPES_ID, us.fok.lenzenslijper.models.jooq.Keys.UNIQ_TARGET_TYPES_SLUG);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public us.fok.lenzenslijper.models.jooq.tables.LinkTargetTypes as(java.lang.String alias) {
		return new us.fok.lenzenslijper.models.jooq.tables.LinkTargetTypes(alias, this);
	}

	/**
	 * Rename this table
	 */
	public us.fok.lenzenslijper.models.jooq.tables.LinkTargetTypes rename(java.lang.String name) {
		return new us.fok.lenzenslijper.models.jooq.tables.LinkTargetTypes(name, null);
	}
}
