/**
 * This class is generated by jOOQ
 */
package us.fok.lenzenslijper.models.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LinkTypes extends org.jooq.impl.TableImpl<us.fok.lenzenslijper.models.jooq.tables.records.LinkTypesRecord> {

	private static final long serialVersionUID = 1442748751;

	/**
	 * The singleton instance of <code>public.link_types</code>
	 */
	public static final us.fok.lenzenslijper.models.jooq.tables.LinkTypes LINK_TYPES = new us.fok.lenzenslijper.models.jooq.tables.LinkTypes();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<us.fok.lenzenslijper.models.jooq.tables.records.LinkTypesRecord> getRecordType() {
		return us.fok.lenzenslijper.models.jooq.tables.records.LinkTypesRecord.class;
	}

	/**
	 * The column <code>public.link_types.link_type_id</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.LinkTypesRecord, java.lang.Integer> LINK_TYPE_ID = createField("link_type_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.link_types.project_id</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.LinkTypesRecord, java.util.UUID> PROJECT_ID = createField("project_id", org.jooq.impl.SQLDataType.UUID.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.link_types.slug</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.LinkTypesRecord, java.lang.String> SLUG = createField("slug", org.jooq.impl.SQLDataType.CLOB.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.link_types.name</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.LinkTypesRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.CLOB.defaulted(true), this, "");

	/**
	 * The column <code>public.link_types.short_name</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.LinkTypesRecord, java.lang.String> SHORT_NAME = createField("short_name", org.jooq.impl.SQLDataType.CLOB.defaulted(true), this, "");

	/**
	 * The column <code>public.link_types.converse_link_type_id</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.LinkTypesRecord, java.lang.Integer> CONVERSE_LINK_TYPE_ID = createField("converse_link_type_id", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "");

	/**
	 * The column <code>public.link_types.link_target_type_id</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.LinkTypesRecord, java.lang.Integer> LINK_TARGET_TYPE_ID = createField("link_target_type_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.link_types.domain_concept_id</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.LinkTypesRecord, java.util.UUID> DOMAIN_CONCEPT_ID = createField("domain_concept_id", org.jooq.impl.SQLDataType.UUID.defaulted(true), this, "");

	/**
	 * The column <code>public.link_types.range_concept_id</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.LinkTypesRecord, java.util.UUID> RANGE_CONCEPT_ID = createField("range_concept_id", org.jooq.impl.SQLDataType.UUID.defaulted(true), this, "");

	/**
	 * The column <code>public.link_types.creator_user_id</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.LinkTypesRecord, java.util.UUID> CREATOR_USER_ID = createField("creator_user_id", org.jooq.impl.SQLDataType.UUID.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.link_types.created</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.LinkTypesRecord, java.sql.Timestamp> CREATED = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.link_types.updater_user_id</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.LinkTypesRecord, java.util.UUID> UPDATER_USER_ID = createField("updater_user_id", org.jooq.impl.SQLDataType.UUID.defaulted(true), this, "");

	/**
	 * The column <code>public.link_types.updated</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.LinkTypesRecord, java.sql.Timestamp> UPDATED = createField("updated", org.jooq.impl.SQLDataType.TIMESTAMP.defaulted(true), this, "");

	/**
	 * The column <code>public.link_types.row_created</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.LinkTypesRecord, java.sql.Timestamp> ROW_CREATED = createField("row_created", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.link_types.row_updated</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.LinkTypesRecord, java.sql.Timestamp> ROW_UPDATED = createField("row_updated", org.jooq.impl.SQLDataType.TIMESTAMP.defaulted(true), this, "");

	/**
	 * Create a <code>public.link_types</code> table reference
	 */
	public LinkTypes() {
		this("link_types", null);
	}

	/**
	 * Create an aliased <code>public.link_types</code> table reference
	 */
	public LinkTypes(java.lang.String alias) {
		this(alias, us.fok.lenzenslijper.models.jooq.tables.LinkTypes.LINK_TYPES);
	}

	private LinkTypes(java.lang.String alias, org.jooq.Table<us.fok.lenzenslijper.models.jooq.tables.records.LinkTypesRecord> aliased) {
		this(alias, aliased, null);
	}

	private LinkTypes(java.lang.String alias, org.jooq.Table<us.fok.lenzenslijper.models.jooq.tables.records.LinkTypesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, us.fok.lenzenslijper.models.jooq.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<us.fok.lenzenslijper.models.jooq.tables.records.LinkTypesRecord, java.lang.Integer> getIdentity() {
		return us.fok.lenzenslijper.models.jooq.Keys.IDENTITY_LINK_TYPES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<us.fok.lenzenslijper.models.jooq.tables.records.LinkTypesRecord> getPrimaryKey() {
		return us.fok.lenzenslijper.models.jooq.Keys.UNIQ_LINK_TYPES_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<us.fok.lenzenslijper.models.jooq.tables.records.LinkTypesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<us.fok.lenzenslijper.models.jooq.tables.records.LinkTypesRecord>>asList(us.fok.lenzenslijper.models.jooq.Keys.UNIQ_LINK_TYPES_ID, us.fok.lenzenslijper.models.jooq.Keys.UNIQ_LINK_TYPES_PROJECT_CONVERSE, us.fok.lenzenslijper.models.jooq.Keys.UNIQ_LINK_TYPES_PROJECT_SLUG);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<us.fok.lenzenslijper.models.jooq.tables.records.LinkTypesRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<us.fok.lenzenslijper.models.jooq.tables.records.LinkTypesRecord, ?>>asList(us.fok.lenzenslijper.models.jooq.Keys.LINK_TYPES__FOR_LINK_TYPES_PROJECT, us.fok.lenzenslijper.models.jooq.Keys.LINK_TYPES__FOR_LINK_TYPES_CONVERSE, us.fok.lenzenslijper.models.jooq.Keys.LINK_TYPES__FOR_LINK_TYPES_TARGET, us.fok.lenzenslijper.models.jooq.Keys.LINK_TYPES__FOR_LINK_TYPES_DOMAIN, us.fok.lenzenslijper.models.jooq.Keys.LINK_TYPES__FOR_LINK_TYPES_RANGE, us.fok.lenzenslijper.models.jooq.Keys.LINK_TYPES__FOR_LINK_TYPES_CREATOR, us.fok.lenzenslijper.models.jooq.Keys.LINK_TYPES__FOR_LINK_TYPES_UPDATER);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public us.fok.lenzenslijper.models.jooq.tables.LinkTypes as(java.lang.String alias) {
		return new us.fok.lenzenslijper.models.jooq.tables.LinkTypes(alias, this);
	}

	/**
	 * Rename this table
	 */
	public us.fok.lenzenslijper.models.jooq.tables.LinkTypes rename(java.lang.String name) {
		return new us.fok.lenzenslijper.models.jooq.tables.LinkTypes(name, null);
	}
}
