/**
 * This class is generated by jOOQ
 */
package us.fok.lenzenslijper.models.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Locations extends org.jooq.impl.TableImpl<us.fok.lenzenslijper.models.jooq.tables.records.LocationsRecord> {

	private static final long serialVersionUID = 693275875;

	/**
	 * The singleton instance of <code>public.locations</code>
	 */
	public static final us.fok.lenzenslijper.models.jooq.tables.Locations LOCATIONS = new us.fok.lenzenslijper.models.jooq.tables.Locations();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<us.fok.lenzenslijper.models.jooq.tables.records.LocationsRecord> getRecordType() {
		return us.fok.lenzenslijper.models.jooq.tables.records.LocationsRecord.class;
	}

	/**
	 * The column <code>public.locations.location_id</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.LocationsRecord, java.util.UUID> LOCATION_ID = createField("location_id", org.jooq.impl.SQLDataType.UUID.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.locations.value</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.LocationsRecord, java.lang.Object> VALUE = createField("value", org.jooq.impl.DefaultDataType.getDefaultDataType("USER-DEFINED"), this, "");

	/**
	 * The column <code>public.locations.row_created</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.LocationsRecord, java.sql.Timestamp> ROW_CREATED = createField("row_created", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>public.locations</code> table reference
	 */
	public Locations() {
		this("locations", null);
	}

	/**
	 * Create an aliased <code>public.locations</code> table reference
	 */
	public Locations(java.lang.String alias) {
		this(alias, us.fok.lenzenslijper.models.jooq.tables.Locations.LOCATIONS);
	}

	private Locations(java.lang.String alias, org.jooq.Table<us.fok.lenzenslijper.models.jooq.tables.records.LocationsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Locations(java.lang.String alias, org.jooq.Table<us.fok.lenzenslijper.models.jooq.tables.records.LocationsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, us.fok.lenzenslijper.models.jooq.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<us.fok.lenzenslijper.models.jooq.tables.records.LocationsRecord> getPrimaryKey() {
		return us.fok.lenzenslijper.models.jooq.Keys.UNIQ_LOCATIONS_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<us.fok.lenzenslijper.models.jooq.tables.records.LocationsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<us.fok.lenzenslijper.models.jooq.tables.records.LocationsRecord>>asList(us.fok.lenzenslijper.models.jooq.Keys.UNIQ_LOCATIONS_ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public us.fok.lenzenslijper.models.jooq.tables.Locations as(java.lang.String alias) {
		return new us.fok.lenzenslijper.models.jooq.tables.Locations(alias, this);
	}

	/**
	 * Rename this table
	 */
	public us.fok.lenzenslijper.models.jooq.tables.Locations rename(java.lang.String name) {
		return new us.fok.lenzenslijper.models.jooq.tables.Locations(name, null);
	}
}
