/**
 * This class is generated by jOOQ
 */
package us.fok.lenzenslijper.models.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Projects extends org.jooq.impl.TableImpl<us.fok.lenzenslijper.models.jooq.tables.records.ProjectsRecord> {

	private static final long serialVersionUID = -11896071;

	/**
	 * The singleton instance of <code>public.projects</code>
	 */
	public static final us.fok.lenzenslijper.models.jooq.tables.Projects PROJECTS = new us.fok.lenzenslijper.models.jooq.tables.Projects();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<us.fok.lenzenslijper.models.jooq.tables.records.ProjectsRecord> getRecordType() {
		return us.fok.lenzenslijper.models.jooq.tables.records.ProjectsRecord.class;
	}

	/**
	 * The column <code>public.projects.project_id</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.ProjectsRecord, java.util.UUID> PROJECT_ID = createField("project_id", org.jooq.impl.SQLDataType.UUID.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.projects.slug</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.ProjectsRecord, java.lang.String> SLUG = createField("slug", org.jooq.impl.SQLDataType.CLOB.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.projects.name</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.ProjectsRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.CLOB.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.projects.short_name</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.ProjectsRecord, java.lang.String> SHORT_NAME = createField("short_name", org.jooq.impl.SQLDataType.CLOB.defaulted(true), this, "");

	/**
	 * The column <code>public.projects.default_mode</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.ProjectsRecord, java.lang.Integer> DEFAULT_MODE = createField("default_mode", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.projects.creator_user_id</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.ProjectsRecord, java.util.UUID> CREATOR_USER_ID = createField("creator_user_id", org.jooq.impl.SQLDataType.UUID.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.projects.created</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.ProjectsRecord, java.sql.Timestamp> CREATED = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.projects.updater_user_id</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.ProjectsRecord, java.util.UUID> UPDATER_USER_ID = createField("updater_user_id", org.jooq.impl.SQLDataType.UUID.defaulted(true), this, "");

	/**
	 * The column <code>public.projects.updated</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.ProjectsRecord, java.sql.Timestamp> UPDATED = createField("updated", org.jooq.impl.SQLDataType.TIMESTAMP.defaulted(true), this, "");

	/**
	 * The column <code>public.projects.row_created</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.ProjectsRecord, java.sql.Timestamp> ROW_CREATED = createField("row_created", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.projects.row_updated</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.ProjectsRecord, java.sql.Timestamp> ROW_UPDATED = createField("row_updated", org.jooq.impl.SQLDataType.TIMESTAMP.defaulted(true), this, "");

	/**
	 * Create a <code>public.projects</code> table reference
	 */
	public Projects() {
		this("projects", null);
	}

	/**
	 * Create an aliased <code>public.projects</code> table reference
	 */
	public Projects(java.lang.String alias) {
		this(alias, us.fok.lenzenslijper.models.jooq.tables.Projects.PROJECTS);
	}

	private Projects(java.lang.String alias, org.jooq.Table<us.fok.lenzenslijper.models.jooq.tables.records.ProjectsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Projects(java.lang.String alias, org.jooq.Table<us.fok.lenzenslijper.models.jooq.tables.records.ProjectsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, us.fok.lenzenslijper.models.jooq.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<us.fok.lenzenslijper.models.jooq.tables.records.ProjectsRecord> getPrimaryKey() {
		return us.fok.lenzenslijper.models.jooq.Keys.UNIQ_PROJECTS_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<us.fok.lenzenslijper.models.jooq.tables.records.ProjectsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<us.fok.lenzenslijper.models.jooq.tables.records.ProjectsRecord>>asList(us.fok.lenzenslijper.models.jooq.Keys.UNIQ_PROJECTS_ID, us.fok.lenzenslijper.models.jooq.Keys.UNIQ_PROJECTS_SLUG);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<us.fok.lenzenslijper.models.jooq.tables.records.ProjectsRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<us.fok.lenzenslijper.models.jooq.tables.records.ProjectsRecord, ?>>asList(us.fok.lenzenslijper.models.jooq.Keys.PROJECTS__FOR_PROJECTS_CREATOR, us.fok.lenzenslijper.models.jooq.Keys.PROJECTS__FOR_PROJECTS_UPDATER);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public us.fok.lenzenslijper.models.jooq.tables.Projects as(java.lang.String alias) {
		return new us.fok.lenzenslijper.models.jooq.tables.Projects(alias, this);
	}

	/**
	 * Rename this table
	 */
	public us.fok.lenzenslijper.models.jooq.tables.Projects rename(java.lang.String name) {
		return new us.fok.lenzenslijper.models.jooq.tables.Projects(name, null);
	}
}
