/**
 * This class is generated by jOOQ
 */
package us.fok.lenzenslijper.models.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PublishedLinkSummaries extends org.jooq.impl.TableImpl<us.fok.lenzenslijper.models.jooq.tables.records.PublishedLinkSummariesRecord> {

	private static final long serialVersionUID = 1940358583;

	/**
	 * The singleton instance of <code>public.published_link_summaries</code>
	 */
	public static final us.fok.lenzenslijper.models.jooq.tables.PublishedLinkSummaries PUBLISHED_LINK_SUMMARIES = new us.fok.lenzenslijper.models.jooq.tables.PublishedLinkSummaries();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<us.fok.lenzenslijper.models.jooq.tables.records.PublishedLinkSummariesRecord> getRecordType() {
		return us.fok.lenzenslijper.models.jooq.tables.records.PublishedLinkSummariesRecord.class;
	}

	/**
	 * The column <code>public.published_link_summaries.revision_id</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.PublishedLinkSummariesRecord, java.util.UUID> REVISION_ID = createField("revision_id", org.jooq.impl.SQLDataType.UUID.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.published_link_summaries.document_id</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.PublishedLinkSummariesRecord, java.util.UUID> DOCUMENT_ID = createField("document_id", org.jooq.impl.SQLDataType.UUID.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.published_link_summaries.link_type_id</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.PublishedLinkSummariesRecord, java.lang.Integer> LINK_TYPE_ID = createField("link_type_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.published_link_summaries.target_title</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.PublishedLinkSummariesRecord, java.lang.String> TARGET_TITLE = createField("target_title", org.jooq.impl.SQLDataType.CLOB.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.published_link_summaries.target_linkable_id</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.PublishedLinkSummariesRecord, java.util.UUID> TARGET_LINKABLE_ID = createField("target_linkable_id", org.jooq.impl.SQLDataType.UUID.defaulted(true), this, "");

	/**
	 * The column <code>public.published_link_summaries.time_range</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.PublishedLinkSummariesRecord, java.lang.String> TIME_RANGE = createField("time_range", org.jooq.impl.SQLDataType.CLOB.defaulted(true), this, "");

	/**
	 * The column <code>public.published_link_summaries.target_value</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.PublishedLinkSummariesRecord, java.lang.String> TARGET_VALUE = createField("target_value", org.jooq.impl.SQLDataType.CLOB.defaulted(true), this, "");

	/**
	 * The column <code>public.published_link_summaries.rank</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.PublishedLinkSummariesRecord, java.lang.Integer> RANK = createField("rank", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "");

	/**
	 * The column <code>public.published_link_summaries.beginning</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.PublishedLinkSummariesRecord, java.lang.Long> BEGINNING = createField("beginning", org.jooq.impl.SQLDataType.BIGINT.defaulted(true), this, "");

	/**
	 * The column <code>public.published_link_summaries.ending</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.PublishedLinkSummariesRecord, java.lang.Long> ENDING = createField("ending", org.jooq.impl.SQLDataType.BIGINT.defaulted(true), this, "");

	/**
	 * Create a <code>public.published_link_summaries</code> table reference
	 */
	public PublishedLinkSummaries() {
		this("published_link_summaries", null);
	}

	/**
	 * Create an aliased <code>public.published_link_summaries</code> table reference
	 */
	public PublishedLinkSummaries(java.lang.String alias) {
		this(alias, us.fok.lenzenslijper.models.jooq.tables.PublishedLinkSummaries.PUBLISHED_LINK_SUMMARIES);
	}

	private PublishedLinkSummaries(java.lang.String alias, org.jooq.Table<us.fok.lenzenslijper.models.jooq.tables.records.PublishedLinkSummariesRecord> aliased) {
		this(alias, aliased, null);
	}

	private PublishedLinkSummaries(java.lang.String alias, org.jooq.Table<us.fok.lenzenslijper.models.jooq.tables.records.PublishedLinkSummariesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, us.fok.lenzenslijper.models.jooq.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<us.fok.lenzenslijper.models.jooq.tables.records.PublishedLinkSummariesRecord> getPrimaryKey() {
		return us.fok.lenzenslijper.models.jooq.Keys.UNIQ_PLINKS_REVISION_LTYPE_TTITLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<us.fok.lenzenslijper.models.jooq.tables.records.PublishedLinkSummariesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<us.fok.lenzenslijper.models.jooq.tables.records.PublishedLinkSummariesRecord>>asList(us.fok.lenzenslijper.models.jooq.Keys.UNIQ_PLINKS_REVISION_LTYPE_TTITLE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<us.fok.lenzenslijper.models.jooq.tables.records.PublishedLinkSummariesRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<us.fok.lenzenslijper.models.jooq.tables.records.PublishedLinkSummariesRecord, ?>>asList(us.fok.lenzenslijper.models.jooq.Keys.PUBLISHED_LINK_SUMMARIES__FOR_PLINKS_REVISION, us.fok.lenzenslijper.models.jooq.Keys.PUBLISHED_LINK_SUMMARIES__FOR_PLINKS_DOCUMENT, us.fok.lenzenslijper.models.jooq.Keys.PUBLISHED_LINK_SUMMARIES__FOR_PLINKS_TYPE, us.fok.lenzenslijper.models.jooq.Keys.PUBLISHED_LINK_SUMMARIES__FOR_PLINKS_LINKABLE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public us.fok.lenzenslijper.models.jooq.tables.PublishedLinkSummaries as(java.lang.String alias) {
		return new us.fok.lenzenslijper.models.jooq.tables.PublishedLinkSummaries(alias, this);
	}

	/**
	 * Rename this table
	 */
	public us.fok.lenzenslijper.models.jooq.tables.PublishedLinkSummaries rename(java.lang.String name) {
		return new us.fok.lenzenslijper.models.jooq.tables.PublishedLinkSummaries(name, null);
	}
}
