/**
 * This class is generated by jOOQ
 */
package us.fok.lenzenslijper.models.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ReleasedTitleSummaries extends org.jooq.impl.TableImpl<us.fok.lenzenslijper.models.jooq.tables.records.ReleasedTitleSummariesRecord> {

	private static final long serialVersionUID = -249379583;

	/**
	 * The singleton instance of <code>public.released_title_summaries</code>
	 */
	public static final us.fok.lenzenslijper.models.jooq.tables.ReleasedTitleSummaries RELEASED_TITLE_SUMMARIES = new us.fok.lenzenslijper.models.jooq.tables.ReleasedTitleSummaries();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<us.fok.lenzenslijper.models.jooq.tables.records.ReleasedTitleSummariesRecord> getRecordType() {
		return us.fok.lenzenslijper.models.jooq.tables.records.ReleasedTitleSummariesRecord.class;
	}

	/**
	 * The column <code>public.released_title_summaries.release_tag_id</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.ReleasedTitleSummariesRecord, java.lang.Integer> RELEASE_TAG_ID = createField("release_tag_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.released_title_summaries.document_id</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.ReleasedTitleSummariesRecord, java.util.UUID> DOCUMENT_ID = createField("document_id", org.jooq.impl.SQLDataType.UUID.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.released_title_summaries.title</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.ReleasedTitleSummariesRecord, java.lang.String> TITLE = createField("title", org.jooq.impl.SQLDataType.CLOB.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>public.released_title_summaries</code> table reference
	 */
	public ReleasedTitleSummaries() {
		this("released_title_summaries", null);
	}

	/**
	 * Create an aliased <code>public.released_title_summaries</code> table reference
	 */
	public ReleasedTitleSummaries(java.lang.String alias) {
		this(alias, us.fok.lenzenslijper.models.jooq.tables.ReleasedTitleSummaries.RELEASED_TITLE_SUMMARIES);
	}

	private ReleasedTitleSummaries(java.lang.String alias, org.jooq.Table<us.fok.lenzenslijper.models.jooq.tables.records.ReleasedTitleSummariesRecord> aliased) {
		this(alias, aliased, null);
	}

	private ReleasedTitleSummaries(java.lang.String alias, org.jooq.Table<us.fok.lenzenslijper.models.jooq.tables.records.ReleasedTitleSummariesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, us.fok.lenzenslijper.models.jooq.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<us.fok.lenzenslijper.models.jooq.tables.records.ReleasedTitleSummariesRecord> getPrimaryKey() {
		return us.fok.lenzenslijper.models.jooq.Keys.UNIQ_REL_TITLES_TAG_DOCUMENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<us.fok.lenzenslijper.models.jooq.tables.records.ReleasedTitleSummariesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<us.fok.lenzenslijper.models.jooq.tables.records.ReleasedTitleSummariesRecord>>asList(us.fok.lenzenslijper.models.jooq.Keys.UNIQ_REL_TITLES_TAG_DOCUMENT);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<us.fok.lenzenslijper.models.jooq.tables.records.ReleasedTitleSummariesRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<us.fok.lenzenslijper.models.jooq.tables.records.ReleasedTitleSummariesRecord, ?>>asList(us.fok.lenzenslijper.models.jooq.Keys.RELEASED_TITLE_SUMMARIES__FOR_REL_TITLES_TAG, us.fok.lenzenslijper.models.jooq.Keys.RELEASED_TITLE_SUMMARIES__FOR_REL_TITLES_DOCUMENT);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public us.fok.lenzenslijper.models.jooq.tables.ReleasedTitleSummaries as(java.lang.String alias) {
		return new us.fok.lenzenslijper.models.jooq.tables.ReleasedTitleSummaries(alias, this);
	}

	/**
	 * Rename this table
	 */
	public us.fok.lenzenslijper.models.jooq.tables.ReleasedTitleSummaries rename(java.lang.String name) {
		return new us.fok.lenzenslijper.models.jooq.tables.ReleasedTitleSummaries(name, null);
	}
}
