/**
 * This class is generated by jOOQ
 */
package us.fok.lenzenslijper.models.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RevisionAssessments extends org.jooq.impl.TableImpl<us.fok.lenzenslijper.models.jooq.tables.records.RevisionAssessmentsRecord> {

	private static final long serialVersionUID = 913854168;

	/**
	 * The singleton instance of <code>public.revision_assessments</code>
	 */
	public static final us.fok.lenzenslijper.models.jooq.tables.RevisionAssessments REVISION_ASSESSMENTS = new us.fok.lenzenslijper.models.jooq.tables.RevisionAssessments();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<us.fok.lenzenslijper.models.jooq.tables.records.RevisionAssessmentsRecord> getRecordType() {
		return us.fok.lenzenslijper.models.jooq.tables.records.RevisionAssessmentsRecord.class;
	}

	/**
	 * The column <code>public.revision_assessments.revision_id</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.RevisionAssessmentsRecord, java.util.UUID> REVISION_ID = createField("revision_id", org.jooq.impl.SQLDataType.UUID.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.revision_assessments.assessment_type_id</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.RevisionAssessmentsRecord, java.lang.Integer> ASSESSMENT_TYPE_ID = createField("assessment_type_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.revision_assessments.user_id</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.RevisionAssessmentsRecord, java.util.UUID> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.UUID.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.revision_assessments.created</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.RevisionAssessmentsRecord, java.sql.Timestamp> CREATED = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.revision_assessments.comments</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.RevisionAssessmentsRecord, java.lang.String> COMMENTS = createField("comments", org.jooq.impl.SQLDataType.CLOB.defaulted(true), this, "");

	/**
	 * The column <code>public.revision_assessments.row_created</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.RevisionAssessmentsRecord, java.sql.Timestamp> ROW_CREATED = createField("row_created", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.revision_assessments.row_updated</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.RevisionAssessmentsRecord, java.sql.Timestamp> ROW_UPDATED = createField("row_updated", org.jooq.impl.SQLDataType.TIMESTAMP.defaulted(true), this, "");

	/**
	 * Create a <code>public.revision_assessments</code> table reference
	 */
	public RevisionAssessments() {
		this("revision_assessments", null);
	}

	/**
	 * Create an aliased <code>public.revision_assessments</code> table reference
	 */
	public RevisionAssessments(java.lang.String alias) {
		this(alias, us.fok.lenzenslijper.models.jooq.tables.RevisionAssessments.REVISION_ASSESSMENTS);
	}

	private RevisionAssessments(java.lang.String alias, org.jooq.Table<us.fok.lenzenslijper.models.jooq.tables.records.RevisionAssessmentsRecord> aliased) {
		this(alias, aliased, null);
	}

	private RevisionAssessments(java.lang.String alias, org.jooq.Table<us.fok.lenzenslijper.models.jooq.tables.records.RevisionAssessmentsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, us.fok.lenzenslijper.models.jooq.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<us.fok.lenzenslijper.models.jooq.tables.records.RevisionAssessmentsRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<us.fok.lenzenslijper.models.jooq.tables.records.RevisionAssessmentsRecord, ?>>asList(us.fok.lenzenslijper.models.jooq.Keys.REVISION_ASSESSMENTS__FOR_REV_ASSESSMENTS_REVISION, us.fok.lenzenslijper.models.jooq.Keys.REVISION_ASSESSMENTS__FOR_REV_ASSESSMENTS_TYPE, us.fok.lenzenslijper.models.jooq.Keys.REVISION_ASSESSMENTS__FOR_REV_ASSESSMENTS_USER);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public us.fok.lenzenslijper.models.jooq.tables.RevisionAssessments as(java.lang.String alias) {
		return new us.fok.lenzenslijper.models.jooq.tables.RevisionAssessments(alias, this);
	}

	/**
	 * Rename this table
	 */
	public us.fok.lenzenslijper.models.jooq.tables.RevisionAssessments rename(java.lang.String name) {
		return new us.fok.lenzenslijper.models.jooq.tables.RevisionAssessments(name, null);
	}
}
