/**
 * This class is generated by jOOQ
 */
package us.fok.lenzenslijper.models.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Revisions extends org.jooq.impl.TableImpl<us.fok.lenzenslijper.models.jooq.tables.records.RevisionsRecord> {

	private static final long serialVersionUID = 745790524;

	/**
	 * The singleton instance of <code>public.revisions</code>
	 */
	public static final us.fok.lenzenslijper.models.jooq.tables.Revisions REVISIONS = new us.fok.lenzenslijper.models.jooq.tables.Revisions();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<us.fok.lenzenslijper.models.jooq.tables.records.RevisionsRecord> getRecordType() {
		return us.fok.lenzenslijper.models.jooq.tables.records.RevisionsRecord.class;
	}

	/**
	 * The column <code>public.revisions.revision_id</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.RevisionsRecord, java.util.UUID> REVISION_ID = createField("revision_id", org.jooq.impl.SQLDataType.UUID.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.revisions.document_id</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.RevisionsRecord, java.util.UUID> DOCUMENT_ID = createField("document_id", org.jooq.impl.SQLDataType.UUID.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.revisions.parent_revision_id</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.RevisionsRecord, java.util.UUID> PARENT_REVISION_ID = createField("parent_revision_id", org.jooq.impl.SQLDataType.UUID.defaulted(true), this, "");

	/**
	 * The column <code>public.revisions.created</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.RevisionsRecord, java.sql.Timestamp> CREATED = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.revisions.user_id</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.RevisionsRecord, java.util.UUID> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.UUID.defaulted(true), this, "");

	/**
	 * The column <code>public.revisions.comments</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.RevisionsRecord, java.lang.String> COMMENTS = createField("comments", org.jooq.impl.SQLDataType.CLOB.defaulted(true), this, "");

	/**
	 * The column <code>public.revisions.row_created</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.RevisionsRecord, java.sql.Timestamp> ROW_CREATED = createField("row_created", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.revisions.row_updated</code>.
	 */
	public final org.jooq.TableField<us.fok.lenzenslijper.models.jooq.tables.records.RevisionsRecord, java.sql.Timestamp> ROW_UPDATED = createField("row_updated", org.jooq.impl.SQLDataType.TIMESTAMP.defaulted(true), this, "");

	/**
	 * Create a <code>public.revisions</code> table reference
	 */
	public Revisions() {
		this("revisions", null);
	}

	/**
	 * Create an aliased <code>public.revisions</code> table reference
	 */
	public Revisions(java.lang.String alias) {
		this(alias, us.fok.lenzenslijper.models.jooq.tables.Revisions.REVISIONS);
	}

	private Revisions(java.lang.String alias, org.jooq.Table<us.fok.lenzenslijper.models.jooq.tables.records.RevisionsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Revisions(java.lang.String alias, org.jooq.Table<us.fok.lenzenslijper.models.jooq.tables.records.RevisionsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, us.fok.lenzenslijper.models.jooq.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<us.fok.lenzenslijper.models.jooq.tables.records.RevisionsRecord> getPrimaryKey() {
		return us.fok.lenzenslijper.models.jooq.Keys.UNIQ_REVISIONS_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<us.fok.lenzenslijper.models.jooq.tables.records.RevisionsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<us.fok.lenzenslijper.models.jooq.tables.records.RevisionsRecord>>asList(us.fok.lenzenslijper.models.jooq.Keys.UNIQ_REVISIONS_ID, us.fok.lenzenslijper.models.jooq.Keys.UNIQ_REVISIONS_DOCUMENT_PARENT);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<us.fok.lenzenslijper.models.jooq.tables.records.RevisionsRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<us.fok.lenzenslijper.models.jooq.tables.records.RevisionsRecord, ?>>asList(us.fok.lenzenslijper.models.jooq.Keys.REVISIONS__FOR_REVISIONS_DOCUMENT, us.fok.lenzenslijper.models.jooq.Keys.REVISIONS__FOR_REVISIONS_PARENT, us.fok.lenzenslijper.models.jooq.Keys.REVISIONS__FOR_REVISIONS_USER);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public us.fok.lenzenslijper.models.jooq.tables.Revisions as(java.lang.String alias) {
		return new us.fok.lenzenslijper.models.jooq.tables.Revisions(alias, this);
	}

	/**
	 * Rename this table
	 */
	public us.fok.lenzenslijper.models.jooq.tables.Revisions rename(java.lang.String name) {
		return new us.fok.lenzenslijper.models.jooq.tables.Revisions(name, null);
	}
}
