/**
 * This class is generated by jOOQ
 */
package us.fok.lenzenslijper.models.jooq.udt;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Addbandarg extends org.jooq.impl.UDTImpl<us.fok.lenzenslijper.models.jooq.udt.records.AddbandargRecord> {

	private static final long serialVersionUID = 1465810771;

	/**
	 * The singleton instance of <code>public.addbandarg</code>
	 */
	public static final us.fok.lenzenslijper.models.jooq.udt.Addbandarg ADDBANDARG = new us.fok.lenzenslijper.models.jooq.udt.Addbandarg();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<us.fok.lenzenslijper.models.jooq.udt.records.AddbandargRecord> getRecordType() {
		return us.fok.lenzenslijper.models.jooq.udt.records.AddbandargRecord.class;
	}

	/**
	 * The attribute <code>public.addbandarg.index</code>.
	 */
	public static final org.jooq.UDTField<us.fok.lenzenslijper.models.jooq.udt.records.AddbandargRecord, java.lang.Integer> INDEX = createField("index", org.jooq.impl.SQLDataType.INTEGER, ADDBANDARG);

	/**
	 * The attribute <code>public.addbandarg.pixeltype</code>.
	 */
	public static final org.jooq.UDTField<us.fok.lenzenslijper.models.jooq.udt.records.AddbandargRecord, java.lang.String> PIXELTYPE = createField("pixeltype", org.jooq.impl.SQLDataType.CLOB, ADDBANDARG);

	/**
	 * The attribute <code>public.addbandarg.initialvalue</code>.
	 */
	public static final org.jooq.UDTField<us.fok.lenzenslijper.models.jooq.udt.records.AddbandargRecord, java.lang.Double> INITIALVALUE = createField("initialvalue", org.jooq.impl.SQLDataType.DOUBLE, ADDBANDARG);

	/**
	 * The attribute <code>public.addbandarg.nodataval</code>.
	 */
	public static final org.jooq.UDTField<us.fok.lenzenslijper.models.jooq.udt.records.AddbandargRecord, java.lang.Double> NODATAVAL = createField("nodataval", org.jooq.impl.SQLDataType.DOUBLE, ADDBANDARG);

	/**
	 * No further instances allowed
	 */
	private Addbandarg() {
		super("addbandarg", us.fok.lenzenslijper.models.jooq.Public.PUBLIC);

		// Initialise data type
		getDataType();
	}
}
