/**
 * This class is generated by jOOQ
 */
package us.fok.lenzenslijper.models.jooq.udt;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Rastbandarg extends org.jooq.impl.UDTImpl<us.fok.lenzenslijper.models.jooq.udt.records.RastbandargRecord> {

	private static final long serialVersionUID = -1335588301;

	/**
	 * The singleton instance of <code>public.rastbandarg</code>
	 */
	public static final us.fok.lenzenslijper.models.jooq.udt.Rastbandarg RASTBANDARG = new us.fok.lenzenslijper.models.jooq.udt.Rastbandarg();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<us.fok.lenzenslijper.models.jooq.udt.records.RastbandargRecord> getRecordType() {
		return us.fok.lenzenslijper.models.jooq.udt.records.RastbandargRecord.class;
	}

	/**
	 * The attribute <code>public.rastbandarg.rast</code>.
	 */
	public static final org.jooq.UDTField<us.fok.lenzenslijper.models.jooq.udt.records.RastbandargRecord, java.lang.Object> RAST = createField("rast", org.jooq.impl.DefaultDataType.getDefaultDataType("USER-DEFINED"), RASTBANDARG);

	/**
	 * The attribute <code>public.rastbandarg.nband</code>.
	 */
	public static final org.jooq.UDTField<us.fok.lenzenslijper.models.jooq.udt.records.RastbandargRecord, java.lang.Integer> NBAND = createField("nband", org.jooq.impl.SQLDataType.INTEGER, RASTBANDARG);

	/**
	 * No further instances allowed
	 */
	private Rastbandarg() {
		super("rastbandarg", us.fok.lenzenslijper.models.jooq.Public.PUBLIC);

		// Initialise data type
		getDataType();
	}
}
