/**
 * This class is generated by jOOQ
 */
package us.fok.lenzenslijper.models.jooq;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in public
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table public.assessment_types
	 */
	public static final us.fok.lenzenslijper.models.jooq.tables.AssessmentTypes ASSESSMENT_TYPES = us.fok.lenzenslijper.models.jooq.tables.AssessmentTypes.ASSESSMENT_TYPES;

	/**
	 * The table public.asset_roles
	 */
	public static final us.fok.lenzenslijper.models.jooq.tables.AssetRoles ASSET_ROLES = us.fok.lenzenslijper.models.jooq.tables.AssetRoles.ASSET_ROLES;

	/**
	 * The table public.asset_types
	 */
	public static final us.fok.lenzenslijper.models.jooq.tables.AssetTypes ASSET_TYPES = us.fok.lenzenslijper.models.jooq.tables.AssetTypes.ASSET_TYPES;

	/**
	 * The table public.assets
	 */
	public static final us.fok.lenzenslijper.models.jooq.tables.Assets ASSETS = us.fok.lenzenslijper.models.jooq.tables.Assets.ASSETS;

	/**
	 * The table public.concept_relation_types
	 */
	public static final us.fok.lenzenslijper.models.jooq.tables.ConceptRelationTypes CONCEPT_RELATION_TYPES = us.fok.lenzenslijper.models.jooq.tables.ConceptRelationTypes.CONCEPT_RELATION_TYPES;

	/**
	 * The table public.concept_relations
	 */
	public static final us.fok.lenzenslijper.models.jooq.tables.ConceptRelations CONCEPT_RELATIONS = us.fok.lenzenslijper.models.jooq.tables.ConceptRelations.CONCEPT_RELATIONS;

	/**
	 * The table public.concept_set_memberships
	 */
	public static final us.fok.lenzenslijper.models.jooq.tables.ConceptSetMemberships CONCEPT_SET_MEMBERSHIPS = us.fok.lenzenslijper.models.jooq.tables.ConceptSetMemberships.CONCEPT_SET_MEMBERSHIPS;

	/**
	 * The table public.concept_sets
	 */
	public static final us.fok.lenzenslijper.models.jooq.tables.ConceptSets CONCEPT_SETS = us.fok.lenzenslijper.models.jooq.tables.ConceptSets.CONCEPT_SETS;

	/**
	 * The table public.concepts
	 */
	public static final us.fok.lenzenslijper.models.jooq.tables.Concepts CONCEPTS = us.fok.lenzenslijper.models.jooq.tables.Concepts.CONCEPTS;

	/**
	 * The table public.document_types
	 */
	public static final us.fok.lenzenslijper.models.jooq.tables.DocumentTypes DOCUMENT_TYPES = us.fok.lenzenslijper.models.jooq.tables.DocumentTypes.DOCUMENT_TYPES;

	/**
	 * The table public.documents
	 */
	public static final us.fok.lenzenslijper.models.jooq.tables.Documents DOCUMENTS = us.fok.lenzenslijper.models.jooq.tables.Documents.DOCUMENTS;

	/**
	 * The table public.entities
	 */
	public static final us.fok.lenzenslijper.models.jooq.tables.Entities ENTITIES = us.fok.lenzenslijper.models.jooq.tables.Entities.ENTITIES;

	/**
	 * The table public.geography_columns
	 */
	public static final us.fok.lenzenslijper.models.jooq.tables.GeographyColumns GEOGRAPHY_COLUMNS = us.fok.lenzenslijper.models.jooq.tables.GeographyColumns.GEOGRAPHY_COLUMNS;

	/**
	 * The table public.geometry_columns
	 */
	public static final us.fok.lenzenslijper.models.jooq.tables.GeometryColumns GEOMETRY_COLUMNS = us.fok.lenzenslijper.models.jooq.tables.GeometryColumns.GEOMETRY_COLUMNS;

	/**
	 * The table public.link_target_types
	 */
	public static final us.fok.lenzenslijper.models.jooq.tables.LinkTargetTypes LINK_TARGET_TYPES = us.fok.lenzenslijper.models.jooq.tables.LinkTargetTypes.LINK_TARGET_TYPES;

	/**
	 * The table public.link_types
	 */
	public static final us.fok.lenzenslijper.models.jooq.tables.LinkTypes LINK_TYPES = us.fok.lenzenslijper.models.jooq.tables.LinkTypes.LINK_TYPES;

	/**
	 * The table public.linkables
	 */
	public static final us.fok.lenzenslijper.models.jooq.tables.Linkables LINKABLES = us.fok.lenzenslijper.models.jooq.tables.Linkables.LINKABLES;

	/**
	 * The table public.locations
	 */
	public static final us.fok.lenzenslijper.models.jooq.tables.Locations LOCATIONS = us.fok.lenzenslijper.models.jooq.tables.Locations.LOCATIONS;

	/**
	 * The table public.project_roles
	 */
	public static final us.fok.lenzenslijper.models.jooq.tables.ProjectRoles PROJECT_ROLES = us.fok.lenzenslijper.models.jooq.tables.ProjectRoles.PROJECT_ROLES;

	/**
	 * The table public.project_user_grants
	 */
	public static final us.fok.lenzenslijper.models.jooq.tables.ProjectUserGrants PROJECT_USER_GRANTS = us.fok.lenzenslijper.models.jooq.tables.ProjectUserGrants.PROJECT_USER_GRANTS;

	/**
	 * The table public.projects
	 */
	public static final us.fok.lenzenslijper.models.jooq.tables.Projects PROJECTS = us.fok.lenzenslijper.models.jooq.tables.Projects.PROJECTS;

	/**
	 * The table public.published_definition_summaries
	 */
	public static final us.fok.lenzenslijper.models.jooq.tables.PublishedDefinitionSummaries PUBLISHED_DEFINITION_SUMMARIES = us.fok.lenzenslijper.models.jooq.tables.PublishedDefinitionSummaries.PUBLISHED_DEFINITION_SUMMARIES;

	/**
	 * The table public.published_link_summaries
	 */
	public static final us.fok.lenzenslijper.models.jooq.tables.PublishedLinkSummaries PUBLISHED_LINK_SUMMARIES = us.fok.lenzenslijper.models.jooq.tables.PublishedLinkSummaries.PUBLISHED_LINK_SUMMARIES;

	/**
	 * The table public.raster_columns
	 */
	public static final us.fok.lenzenslijper.models.jooq.tables.RasterColumns RASTER_COLUMNS = us.fok.lenzenslijper.models.jooq.tables.RasterColumns.RASTER_COLUMNS;

	/**
	 * The table public.raster_overviews
	 */
	public static final us.fok.lenzenslijper.models.jooq.tables.RasterOverviews RASTER_OVERVIEWS = us.fok.lenzenslijper.models.jooq.tables.RasterOverviews.RASTER_OVERVIEWS;

	/**
	 * The table public.release_tags
	 */
	public static final us.fok.lenzenslijper.models.jooq.tables.ReleaseTags RELEASE_TAGS = us.fok.lenzenslijper.models.jooq.tables.ReleaseTags.RELEASE_TAGS;

	/**
	 * The table public.released_revision_summaries
	 */
	public static final us.fok.lenzenslijper.models.jooq.tables.ReleasedRevisionSummaries RELEASED_REVISION_SUMMARIES = us.fok.lenzenslijper.models.jooq.tables.ReleasedRevisionSummaries.RELEASED_REVISION_SUMMARIES;

	/**
	 * The table public.released_title_summaries
	 */
	public static final us.fok.lenzenslijper.models.jooq.tables.ReleasedTitleSummaries RELEASED_TITLE_SUMMARIES = us.fok.lenzenslijper.models.jooq.tables.ReleasedTitleSummaries.RELEASED_TITLE_SUMMARIES;

	/**
	 * The table public.revision_assessments
	 */
	public static final us.fok.lenzenslijper.models.jooq.tables.RevisionAssessments REVISION_ASSESSMENTS = us.fok.lenzenslijper.models.jooq.tables.RevisionAssessments.REVISION_ASSESSMENTS;

	/**
	 * The table public.revision_asset_roles
	 */
	public static final us.fok.lenzenslijper.models.jooq.tables.RevisionAssetRoles REVISION_ASSET_ROLES = us.fok.lenzenslijper.models.jooq.tables.RevisionAssetRoles.REVISION_ASSET_ROLES;

	/**
	 * The table public.revision_links
	 */
	public static final us.fok.lenzenslijper.models.jooq.tables.RevisionLinks REVISION_LINKS = us.fok.lenzenslijper.models.jooq.tables.RevisionLinks.REVISION_LINKS;

	/**
	 * The table public.revisions
	 */
	public static final us.fok.lenzenslijper.models.jooq.tables.Revisions REVISIONS = us.fok.lenzenslijper.models.jooq.tables.Revisions.REVISIONS;

	/**
	 * The table public.spatial_ref_sys
	 */
	public static final us.fok.lenzenslijper.models.jooq.tables.SpatialRefSys SPATIAL_REF_SYS = us.fok.lenzenslijper.models.jooq.tables.SpatialRefSys.SPATIAL_REF_SYS;

	/**
	 * The table public.submitted_definition_summaries
	 */
	public static final us.fok.lenzenslijper.models.jooq.tables.SubmittedDefinitionSummaries SUBMITTED_DEFINITION_SUMMARIES = us.fok.lenzenslijper.models.jooq.tables.SubmittedDefinitionSummaries.SUBMITTED_DEFINITION_SUMMARIES;

	/**
	 * The table public.submitted_link_summaries
	 */
	public static final us.fok.lenzenslijper.models.jooq.tables.SubmittedLinkSummaries SUBMITTED_LINK_SUMMARIES = us.fok.lenzenslijper.models.jooq.tables.SubmittedLinkSummaries.SUBMITTED_LINK_SUMMARIES;

	/**
	 * The table public.user_preferences
	 */
	public static final us.fok.lenzenslijper.models.jooq.tables.UserPreferences USER_PREFERENCES = us.fok.lenzenslijper.models.jooq.tables.UserPreferences.USER_PREFERENCES;

	/**
	 * The table public.users
	 */
	public static final us.fok.lenzenslijper.models.jooq.tables.Users USERS = us.fok.lenzenslijper.models.jooq.tables.Users.USERS;

	/**
	 * The table public.virtual_aggregate_grants
	 */
	public static final us.fok.lenzenslijper.models.jooq.tables.VirtualAggregateGrants VIRTUAL_AGGREGATE_GRANTS = us.fok.lenzenslijper.models.jooq.tables.VirtualAggregateGrants.VIRTUAL_AGGREGATE_GRANTS;
}
