/**
 * This class is generated by jOOQ
 */
package us.fok.lenzenslijper.models.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AssetsRecord extends org.jooq.impl.UpdatableRecordImpl<us.fok.lenzenslijper.models.jooq.tables.records.AssetsRecord> implements org.jooq.Record6<java.util.UUID, java.lang.Integer, java.lang.String, byte[], java.sql.Timestamp, java.sql.Timestamp> {

	private static final long serialVersionUID = 2141749132;

	/**
	 * Setter for <code>public.assets.asset_id</code>.
	 */
	public void setAssetId(java.util.UUID value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.assets.asset_id</code>.
	 */
	public java.util.UUID getAssetId() {
		return (java.util.UUID) getValue(0);
	}

	/**
	 * Setter for <code>public.assets.asset_type_id</code>.
	 */
	public void setAssetTypeId(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.assets.asset_type_id</code>.
	 */
	public java.lang.Integer getAssetTypeId() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>public.assets.digest</code>.
	 */
	public void setDigest(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.assets.digest</code>.
	 */
	public java.lang.String getDigest() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>public.assets.content</code>.
	 */
	public void setContent(byte[] value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.assets.content</code>.
	 */
	public byte[] getContent() {
		return (byte[]) getValue(3);
	}

	/**
	 * Setter for <code>public.assets.row_created</code>.
	 */
	public void setRowCreated(java.sql.Timestamp value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.assets.row_created</code>.
	 */
	public java.sql.Timestamp getRowCreated() {
		return (java.sql.Timestamp) getValue(4);
	}

	/**
	 * Setter for <code>public.assets.row_updated</code>.
	 */
	public void setRowUpdated(java.sql.Timestamp value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.assets.row_updated</code>.
	 */
	public java.sql.Timestamp getRowUpdated() {
		return (java.sql.Timestamp) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.util.UUID> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.util.UUID, java.lang.Integer, java.lang.String, byte[], java.sql.Timestamp, java.sql.Timestamp> fieldsRow() {
		return (org.jooq.Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.util.UUID, java.lang.Integer, java.lang.String, byte[], java.sql.Timestamp, java.sql.Timestamp> valuesRow() {
		return (org.jooq.Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field1() {
		return us.fok.lenzenslijper.models.jooq.tables.Assets.ASSETS.ASSET_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return us.fok.lenzenslijper.models.jooq.tables.Assets.ASSETS.ASSET_TYPE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return us.fok.lenzenslijper.models.jooq.tables.Assets.ASSETS.DIGEST;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<byte[]> field4() {
		return us.fok.lenzenslijper.models.jooq.tables.Assets.ASSETS.CONTENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field5() {
		return us.fok.lenzenslijper.models.jooq.tables.Assets.ASSETS.ROW_CREATED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field6() {
		return us.fok.lenzenslijper.models.jooq.tables.Assets.ASSETS.ROW_UPDATED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value1() {
		return getAssetId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getAssetTypeId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getDigest();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public byte[] value4() {
		return getContent();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value5() {
		return getRowCreated();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value6() {
		return getRowUpdated();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AssetsRecord value1(java.util.UUID value) {
		setAssetId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AssetsRecord value2(java.lang.Integer value) {
		setAssetTypeId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AssetsRecord value3(java.lang.String value) {
		setDigest(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AssetsRecord value4(byte[] value) {
		setContent(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AssetsRecord value5(java.sql.Timestamp value) {
		setRowCreated(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AssetsRecord value6(java.sql.Timestamp value) {
		setRowUpdated(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AssetsRecord values(java.util.UUID value1, java.lang.Integer value2, java.lang.String value3, byte[] value4, java.sql.Timestamp value5, java.sql.Timestamp value6) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AssetsRecord
	 */
	public AssetsRecord() {
		super(us.fok.lenzenslijper.models.jooq.tables.Assets.ASSETS);
	}

	/**
	 * Create a detached, initialised AssetsRecord
	 */
	public AssetsRecord(java.util.UUID assetId, java.lang.Integer assetTypeId, java.lang.String digest, byte[] content, java.sql.Timestamp rowCreated, java.sql.Timestamp rowUpdated) {
		super(us.fok.lenzenslijper.models.jooq.tables.Assets.ASSETS);

		setValue(0, assetId);
		setValue(1, assetTypeId);
		setValue(2, digest);
		setValue(3, content);
		setValue(4, rowCreated);
		setValue(5, rowUpdated);
	}
}
