/**
 * This class is generated by jOOQ
 */
package us.fok.lenzenslijper.models.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ConceptRelationTypesRecord extends org.jooq.impl.UpdatableRecordImpl<us.fok.lenzenslijper.models.jooq.tables.records.ConceptRelationTypesRecord> implements org.jooq.Record11<java.lang.Integer, java.util.UUID, java.lang.String, java.lang.String, java.lang.String, java.util.UUID, java.sql.Timestamp, java.util.UUID, java.sql.Timestamp, java.sql.Timestamp, java.sql.Timestamp> {

	private static final long serialVersionUID = -101801675;

	/**
	 * Setter for <code>public.concept_relation_types.concept_relation_type_id</code>.
	 */
	public void setConceptRelationTypeId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.concept_relation_types.concept_relation_type_id</code>.
	 */
	public java.lang.Integer getConceptRelationTypeId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.concept_relation_types.project_id</code>.
	 */
	public void setProjectId(java.util.UUID value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.concept_relation_types.project_id</code>.
	 */
	public java.util.UUID getProjectId() {
		return (java.util.UUID) getValue(1);
	}

	/**
	 * Setter for <code>public.concept_relation_types.slug</code>.
	 */
	public void setSlug(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.concept_relation_types.slug</code>.
	 */
	public java.lang.String getSlug() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>public.concept_relation_types.name</code>.
	 */
	public void setName(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.concept_relation_types.name</code>.
	 */
	public java.lang.String getName() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>public.concept_relation_types.short_name</code>.
	 */
	public void setShortName(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.concept_relation_types.short_name</code>.
	 */
	public java.lang.String getShortName() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>public.concept_relation_types.creator_user_id</code>.
	 */
	public void setCreatorUserId(java.util.UUID value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.concept_relation_types.creator_user_id</code>.
	 */
	public java.util.UUID getCreatorUserId() {
		return (java.util.UUID) getValue(5);
	}

	/**
	 * Setter for <code>public.concept_relation_types.created</code>.
	 */
	public void setCreated(java.sql.Timestamp value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>public.concept_relation_types.created</code>.
	 */
	public java.sql.Timestamp getCreated() {
		return (java.sql.Timestamp) getValue(6);
	}

	/**
	 * Setter for <code>public.concept_relation_types.updater_user_id</code>.
	 */
	public void setUpdaterUserId(java.util.UUID value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>public.concept_relation_types.updater_user_id</code>.
	 */
	public java.util.UUID getUpdaterUserId() {
		return (java.util.UUID) getValue(7);
	}

	/**
	 * Setter for <code>public.concept_relation_types.updated</code>.
	 */
	public void setUpdated(java.sql.Timestamp value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>public.concept_relation_types.updated</code>.
	 */
	public java.sql.Timestamp getUpdated() {
		return (java.sql.Timestamp) getValue(8);
	}

	/**
	 * Setter for <code>public.concept_relation_types.row_created</code>.
	 */
	public void setRowCreated(java.sql.Timestamp value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>public.concept_relation_types.row_created</code>.
	 */
	public java.sql.Timestamp getRowCreated() {
		return (java.sql.Timestamp) getValue(9);
	}

	/**
	 * Setter for <code>public.concept_relation_types.row_updated</code>.
	 */
	public void setRowUpdated(java.sql.Timestamp value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>public.concept_relation_types.row_updated</code>.
	 */
	public java.sql.Timestamp getRowUpdated() {
		return (java.sql.Timestamp) getValue(10);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record11 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row11<java.lang.Integer, java.util.UUID, java.lang.String, java.lang.String, java.lang.String, java.util.UUID, java.sql.Timestamp, java.util.UUID, java.sql.Timestamp, java.sql.Timestamp, java.sql.Timestamp> fieldsRow() {
		return (org.jooq.Row11) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row11<java.lang.Integer, java.util.UUID, java.lang.String, java.lang.String, java.lang.String, java.util.UUID, java.sql.Timestamp, java.util.UUID, java.sql.Timestamp, java.sql.Timestamp, java.sql.Timestamp> valuesRow() {
		return (org.jooq.Row11) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return us.fok.lenzenslijper.models.jooq.tables.ConceptRelationTypes.CONCEPT_RELATION_TYPES.CONCEPT_RELATION_TYPE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field2() {
		return us.fok.lenzenslijper.models.jooq.tables.ConceptRelationTypes.CONCEPT_RELATION_TYPES.PROJECT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return us.fok.lenzenslijper.models.jooq.tables.ConceptRelationTypes.CONCEPT_RELATION_TYPES.SLUG;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return us.fok.lenzenslijper.models.jooq.tables.ConceptRelationTypes.CONCEPT_RELATION_TYPES.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return us.fok.lenzenslijper.models.jooq.tables.ConceptRelationTypes.CONCEPT_RELATION_TYPES.SHORT_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field6() {
		return us.fok.lenzenslijper.models.jooq.tables.ConceptRelationTypes.CONCEPT_RELATION_TYPES.CREATOR_USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field7() {
		return us.fok.lenzenslijper.models.jooq.tables.ConceptRelationTypes.CONCEPT_RELATION_TYPES.CREATED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field8() {
		return us.fok.lenzenslijper.models.jooq.tables.ConceptRelationTypes.CONCEPT_RELATION_TYPES.UPDATER_USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field9() {
		return us.fok.lenzenslijper.models.jooq.tables.ConceptRelationTypes.CONCEPT_RELATION_TYPES.UPDATED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field10() {
		return us.fok.lenzenslijper.models.jooq.tables.ConceptRelationTypes.CONCEPT_RELATION_TYPES.ROW_CREATED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field11() {
		return us.fok.lenzenslijper.models.jooq.tables.ConceptRelationTypes.CONCEPT_RELATION_TYPES.ROW_UPDATED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getConceptRelationTypeId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value2() {
		return getProjectId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getSlug();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getShortName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value6() {
		return getCreatorUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value7() {
		return getCreated();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value8() {
		return getUpdaterUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value9() {
		return getUpdated();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value10() {
		return getRowCreated();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value11() {
		return getRowUpdated();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ConceptRelationTypesRecord value1(java.lang.Integer value) {
		setConceptRelationTypeId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ConceptRelationTypesRecord value2(java.util.UUID value) {
		setProjectId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ConceptRelationTypesRecord value3(java.lang.String value) {
		setSlug(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ConceptRelationTypesRecord value4(java.lang.String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ConceptRelationTypesRecord value5(java.lang.String value) {
		setShortName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ConceptRelationTypesRecord value6(java.util.UUID value) {
		setCreatorUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ConceptRelationTypesRecord value7(java.sql.Timestamp value) {
		setCreated(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ConceptRelationTypesRecord value8(java.util.UUID value) {
		setUpdaterUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ConceptRelationTypesRecord value9(java.sql.Timestamp value) {
		setUpdated(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ConceptRelationTypesRecord value10(java.sql.Timestamp value) {
		setRowCreated(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ConceptRelationTypesRecord value11(java.sql.Timestamp value) {
		setRowUpdated(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ConceptRelationTypesRecord values(java.lang.Integer value1, java.util.UUID value2, java.lang.String value3, java.lang.String value4, java.lang.String value5, java.util.UUID value6, java.sql.Timestamp value7, java.util.UUID value8, java.sql.Timestamp value9, java.sql.Timestamp value10, java.sql.Timestamp value11) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ConceptRelationTypesRecord
	 */
	public ConceptRelationTypesRecord() {
		super(us.fok.lenzenslijper.models.jooq.tables.ConceptRelationTypes.CONCEPT_RELATION_TYPES);
	}

	/**
	 * Create a detached, initialised ConceptRelationTypesRecord
	 */
	public ConceptRelationTypesRecord(java.lang.Integer conceptRelationTypeId, java.util.UUID projectId, java.lang.String slug, java.lang.String name, java.lang.String shortName, java.util.UUID creatorUserId, java.sql.Timestamp created, java.util.UUID updaterUserId, java.sql.Timestamp updated, java.sql.Timestamp rowCreated, java.sql.Timestamp rowUpdated) {
		super(us.fok.lenzenslijper.models.jooq.tables.ConceptRelationTypes.CONCEPT_RELATION_TYPES);

		setValue(0, conceptRelationTypeId);
		setValue(1, projectId);
		setValue(2, slug);
		setValue(3, name);
		setValue(4, shortName);
		setValue(5, creatorUserId);
		setValue(6, created);
		setValue(7, updaterUserId);
		setValue(8, updated);
		setValue(9, rowCreated);
		setValue(10, rowUpdated);
	}
}
