/**
 * This class is generated by jOOQ
 */
package us.fok.lenzenslijper.models.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ConceptRelationsRecord extends org.jooq.impl.UpdatableRecordImpl<us.fok.lenzenslijper.models.jooq.tables.records.ConceptRelationsRecord> implements org.jooq.Record8<java.util.UUID, java.util.UUID, java.lang.Integer, java.util.UUID, java.util.UUID, java.sql.Timestamp, java.sql.Timestamp, java.sql.Timestamp> {

	private static final long serialVersionUID = -1136019466;

	/**
	 * Setter for <code>public.concept_relations.project_id</code>.
	 */
	public void setProjectId(java.util.UUID value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.concept_relations.project_id</code>.
	 */
	public java.util.UUID getProjectId() {
		return (java.util.UUID) getValue(0);
	}

	/**
	 * Setter for <code>public.concept_relations.concept_id</code>.
	 */
	public void setConceptId(java.util.UUID value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.concept_relations.concept_id</code>.
	 */
	public java.util.UUID getConceptId() {
		return (java.util.UUID) getValue(1);
	}

	/**
	 * Setter for <code>public.concept_relations.concept_relation_type_id</code>.
	 */
	public void setConceptRelationTypeId(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.concept_relations.concept_relation_type_id</code>.
	 */
	public java.lang.Integer getConceptRelationTypeId() {
		return (java.lang.Integer) getValue(2);
	}

	/**
	 * Setter for <code>public.concept_relations.related_concept_id</code>.
	 */
	public void setRelatedConceptId(java.util.UUID value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.concept_relations.related_concept_id</code>.
	 */
	public java.util.UUID getRelatedConceptId() {
		return (java.util.UUID) getValue(3);
	}

	/**
	 * Setter for <code>public.concept_relations.creator_user_id</code>.
	 */
	public void setCreatorUserId(java.util.UUID value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.concept_relations.creator_user_id</code>.
	 */
	public java.util.UUID getCreatorUserId() {
		return (java.util.UUID) getValue(4);
	}

	/**
	 * Setter for <code>public.concept_relations.created</code>.
	 */
	public void setCreated(java.sql.Timestamp value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.concept_relations.created</code>.
	 */
	public java.sql.Timestamp getCreated() {
		return (java.sql.Timestamp) getValue(5);
	}

	/**
	 * Setter for <code>public.concept_relations.row_created</code>.
	 */
	public void setRowCreated(java.sql.Timestamp value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>public.concept_relations.row_created</code>.
	 */
	public java.sql.Timestamp getRowCreated() {
		return (java.sql.Timestamp) getValue(6);
	}

	/**
	 * Setter for <code>public.concept_relations.row_updated</code>.
	 */
	public void setRowUpdated(java.sql.Timestamp value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>public.concept_relations.row_updated</code>.
	 */
	public java.sql.Timestamp getRowUpdated() {
		return (java.sql.Timestamp) getValue(7);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record4<java.util.UUID, java.util.UUID, java.lang.Integer, java.util.UUID> key() {
		return (org.jooq.Record4) super.key();
	}

	// -------------------------------------------------------------------------
	// Record8 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row8<java.util.UUID, java.util.UUID, java.lang.Integer, java.util.UUID, java.util.UUID, java.sql.Timestamp, java.sql.Timestamp, java.sql.Timestamp> fieldsRow() {
		return (org.jooq.Row8) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row8<java.util.UUID, java.util.UUID, java.lang.Integer, java.util.UUID, java.util.UUID, java.sql.Timestamp, java.sql.Timestamp, java.sql.Timestamp> valuesRow() {
		return (org.jooq.Row8) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field1() {
		return us.fok.lenzenslijper.models.jooq.tables.ConceptRelations.CONCEPT_RELATIONS.PROJECT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field2() {
		return us.fok.lenzenslijper.models.jooq.tables.ConceptRelations.CONCEPT_RELATIONS.CONCEPT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return us.fok.lenzenslijper.models.jooq.tables.ConceptRelations.CONCEPT_RELATIONS.CONCEPT_RELATION_TYPE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field4() {
		return us.fok.lenzenslijper.models.jooq.tables.ConceptRelations.CONCEPT_RELATIONS.RELATED_CONCEPT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field5() {
		return us.fok.lenzenslijper.models.jooq.tables.ConceptRelations.CONCEPT_RELATIONS.CREATOR_USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field6() {
		return us.fok.lenzenslijper.models.jooq.tables.ConceptRelations.CONCEPT_RELATIONS.CREATED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field7() {
		return us.fok.lenzenslijper.models.jooq.tables.ConceptRelations.CONCEPT_RELATIONS.ROW_CREATED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field8() {
		return us.fok.lenzenslijper.models.jooq.tables.ConceptRelations.CONCEPT_RELATIONS.ROW_UPDATED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value1() {
		return getProjectId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value2() {
		return getConceptId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getConceptRelationTypeId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value4() {
		return getRelatedConceptId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value5() {
		return getCreatorUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value6() {
		return getCreated();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value7() {
		return getRowCreated();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value8() {
		return getRowUpdated();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ConceptRelationsRecord value1(java.util.UUID value) {
		setProjectId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ConceptRelationsRecord value2(java.util.UUID value) {
		setConceptId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ConceptRelationsRecord value3(java.lang.Integer value) {
		setConceptRelationTypeId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ConceptRelationsRecord value4(java.util.UUID value) {
		setRelatedConceptId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ConceptRelationsRecord value5(java.util.UUID value) {
		setCreatorUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ConceptRelationsRecord value6(java.sql.Timestamp value) {
		setCreated(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ConceptRelationsRecord value7(java.sql.Timestamp value) {
		setRowCreated(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ConceptRelationsRecord value8(java.sql.Timestamp value) {
		setRowUpdated(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ConceptRelationsRecord values(java.util.UUID value1, java.util.UUID value2, java.lang.Integer value3, java.util.UUID value4, java.util.UUID value5, java.sql.Timestamp value6, java.sql.Timestamp value7, java.sql.Timestamp value8) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ConceptRelationsRecord
	 */
	public ConceptRelationsRecord() {
		super(us.fok.lenzenslijper.models.jooq.tables.ConceptRelations.CONCEPT_RELATIONS);
	}

	/**
	 * Create a detached, initialised ConceptRelationsRecord
	 */
	public ConceptRelationsRecord(java.util.UUID projectId, java.util.UUID conceptId, java.lang.Integer conceptRelationTypeId, java.util.UUID relatedConceptId, java.util.UUID creatorUserId, java.sql.Timestamp created, java.sql.Timestamp rowCreated, java.sql.Timestamp rowUpdated) {
		super(us.fok.lenzenslijper.models.jooq.tables.ConceptRelations.CONCEPT_RELATIONS);

		setValue(0, projectId);
		setValue(1, conceptId);
		setValue(2, conceptRelationTypeId);
		setValue(3, relatedConceptId);
		setValue(4, creatorUserId);
		setValue(5, created);
		setValue(6, rowCreated);
		setValue(7, rowUpdated);
	}
}
