/**
 * This class is generated by jOOQ
 */
package us.fok.lenzenslijper.models.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LinkablesRecord extends org.jooq.impl.UpdatableRecordImpl<us.fok.lenzenslijper.models.jooq.tables.records.LinkablesRecord> implements org.jooq.Record7<java.util.UUID, java.util.UUID, java.util.UUID, java.util.UUID, java.util.UUID, java.sql.Timestamp, java.sql.Timestamp> {

	private static final long serialVersionUID = -605258734;

	/**
	 * Setter for <code>public.linkables.linkable_id</code>.
	 */
	public void setLinkableId(java.util.UUID value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.linkables.linkable_id</code>.
	 */
	public java.util.UUID getLinkableId() {
		return (java.util.UUID) getValue(0);
	}

	/**
	 * Setter for <code>public.linkables.entity_id</code>.
	 */
	public void setEntityId(java.util.UUID value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.linkables.entity_id</code>.
	 */
	public java.util.UUID getEntityId() {
		return (java.util.UUID) getValue(1);
	}

	/**
	 * Setter for <code>public.linkables.concept_id</code>.
	 */
	public void setConceptId(java.util.UUID value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.linkables.concept_id</code>.
	 */
	public java.util.UUID getConceptId() {
		return (java.util.UUID) getValue(2);
	}

	/**
	 * Setter for <code>public.linkables.document_id</code>.
	 */
	public void setDocumentId(java.util.UUID value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.linkables.document_id</code>.
	 */
	public java.util.UUID getDocumentId() {
		return (java.util.UUID) getValue(3);
	}

	/**
	 * Setter for <code>public.linkables.location_id</code>.
	 */
	public void setLocationId(java.util.UUID value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.linkables.location_id</code>.
	 */
	public java.util.UUID getLocationId() {
		return (java.util.UUID) getValue(4);
	}

	/**
	 * Setter for <code>public.linkables.row_created</code>.
	 */
	public void setRowCreated(java.sql.Timestamp value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.linkables.row_created</code>.
	 */
	public java.sql.Timestamp getRowCreated() {
		return (java.sql.Timestamp) getValue(5);
	}

	/**
	 * Setter for <code>public.linkables.row_updated</code>.
	 */
	public void setRowUpdated(java.sql.Timestamp value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>public.linkables.row_updated</code>.
	 */
	public java.sql.Timestamp getRowUpdated() {
		return (java.sql.Timestamp) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.util.UUID> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.util.UUID, java.util.UUID, java.util.UUID, java.util.UUID, java.util.UUID, java.sql.Timestamp, java.sql.Timestamp> fieldsRow() {
		return (org.jooq.Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.util.UUID, java.util.UUID, java.util.UUID, java.util.UUID, java.util.UUID, java.sql.Timestamp, java.sql.Timestamp> valuesRow() {
		return (org.jooq.Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field1() {
		return us.fok.lenzenslijper.models.jooq.tables.Linkables.LINKABLES.LINKABLE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field2() {
		return us.fok.lenzenslijper.models.jooq.tables.Linkables.LINKABLES.ENTITY_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field3() {
		return us.fok.lenzenslijper.models.jooq.tables.Linkables.LINKABLES.CONCEPT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field4() {
		return us.fok.lenzenslijper.models.jooq.tables.Linkables.LINKABLES.DOCUMENT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field5() {
		return us.fok.lenzenslijper.models.jooq.tables.Linkables.LINKABLES.LOCATION_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field6() {
		return us.fok.lenzenslijper.models.jooq.tables.Linkables.LINKABLES.ROW_CREATED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field7() {
		return us.fok.lenzenslijper.models.jooq.tables.Linkables.LINKABLES.ROW_UPDATED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value1() {
		return getLinkableId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value2() {
		return getEntityId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value3() {
		return getConceptId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value4() {
		return getDocumentId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value5() {
		return getLocationId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value6() {
		return getRowCreated();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value7() {
		return getRowUpdated();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LinkablesRecord value1(java.util.UUID value) {
		setLinkableId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LinkablesRecord value2(java.util.UUID value) {
		setEntityId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LinkablesRecord value3(java.util.UUID value) {
		setConceptId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LinkablesRecord value4(java.util.UUID value) {
		setDocumentId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LinkablesRecord value5(java.util.UUID value) {
		setLocationId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LinkablesRecord value6(java.sql.Timestamp value) {
		setRowCreated(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LinkablesRecord value7(java.sql.Timestamp value) {
		setRowUpdated(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LinkablesRecord values(java.util.UUID value1, java.util.UUID value2, java.util.UUID value3, java.util.UUID value4, java.util.UUID value5, java.sql.Timestamp value6, java.sql.Timestamp value7) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached LinkablesRecord
	 */
	public LinkablesRecord() {
		super(us.fok.lenzenslijper.models.jooq.tables.Linkables.LINKABLES);
	}

	/**
	 * Create a detached, initialised LinkablesRecord
	 */
	public LinkablesRecord(java.util.UUID linkableId, java.util.UUID entityId, java.util.UUID conceptId, java.util.UUID documentId, java.util.UUID locationId, java.sql.Timestamp rowCreated, java.sql.Timestamp rowUpdated) {
		super(us.fok.lenzenslijper.models.jooq.tables.Linkables.LINKABLES);

		setValue(0, linkableId);
		setValue(1, entityId);
		setValue(2, conceptId);
		setValue(3, documentId);
		setValue(4, locationId);
		setValue(5, rowCreated);
		setValue(6, rowUpdated);
	}
}
