/**
 * This class is generated by jOOQ
 */
package us.fok.lenzenslijper.models.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProjectUserGrantsRecord extends org.jooq.impl.UpdatableRecordImpl<us.fok.lenzenslijper.models.jooq.tables.records.ProjectUserGrantsRecord> implements org.jooq.Record7<java.util.UUID, java.util.UUID, java.lang.Integer, java.util.UUID, java.sql.Timestamp, java.sql.Timestamp, java.sql.Timestamp> {

	private static final long serialVersionUID = 941453193;

	/**
	 * Setter for <code>public.project_user_grants.project_id</code>.
	 */
	public void setProjectId(java.util.UUID value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.project_user_grants.project_id</code>.
	 */
	public java.util.UUID getProjectId() {
		return (java.util.UUID) getValue(0);
	}

	/**
	 * Setter for <code>public.project_user_grants.user_id</code>.
	 */
	public void setUserId(java.util.UUID value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.project_user_grants.user_id</code>.
	 */
	public java.util.UUID getUserId() {
		return (java.util.UUID) getValue(1);
	}

	/**
	 * Setter for <code>public.project_user_grants.project_role_id</code>.
	 */
	public void setProjectRoleId(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.project_user_grants.project_role_id</code>.
	 */
	public java.lang.Integer getProjectRoleId() {
		return (java.lang.Integer) getValue(2);
	}

	/**
	 * Setter for <code>public.project_user_grants.grantor_user_id</code>.
	 */
	public void setGrantorUserId(java.util.UUID value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.project_user_grants.grantor_user_id</code>.
	 */
	public java.util.UUID getGrantorUserId() {
		return (java.util.UUID) getValue(3);
	}

	/**
	 * Setter for <code>public.project_user_grants.created</code>.
	 */
	public void setCreated(java.sql.Timestamp value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.project_user_grants.created</code>.
	 */
	public java.sql.Timestamp getCreated() {
		return (java.sql.Timestamp) getValue(4);
	}

	/**
	 * Setter for <code>public.project_user_grants.row_created</code>.
	 */
	public void setRowCreated(java.sql.Timestamp value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.project_user_grants.row_created</code>.
	 */
	public java.sql.Timestamp getRowCreated() {
		return (java.sql.Timestamp) getValue(5);
	}

	/**
	 * Setter for <code>public.project_user_grants.row_updated</code>.
	 */
	public void setRowUpdated(java.sql.Timestamp value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>public.project_user_grants.row_updated</code>.
	 */
	public java.sql.Timestamp getRowUpdated() {
		return (java.sql.Timestamp) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record3<java.util.UUID, java.util.UUID, java.lang.Integer> key() {
		return (org.jooq.Record3) super.key();
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.util.UUID, java.util.UUID, java.lang.Integer, java.util.UUID, java.sql.Timestamp, java.sql.Timestamp, java.sql.Timestamp> fieldsRow() {
		return (org.jooq.Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.util.UUID, java.util.UUID, java.lang.Integer, java.util.UUID, java.sql.Timestamp, java.sql.Timestamp, java.sql.Timestamp> valuesRow() {
		return (org.jooq.Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field1() {
		return us.fok.lenzenslijper.models.jooq.tables.ProjectUserGrants.PROJECT_USER_GRANTS.PROJECT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field2() {
		return us.fok.lenzenslijper.models.jooq.tables.ProjectUserGrants.PROJECT_USER_GRANTS.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return us.fok.lenzenslijper.models.jooq.tables.ProjectUserGrants.PROJECT_USER_GRANTS.PROJECT_ROLE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field4() {
		return us.fok.lenzenslijper.models.jooq.tables.ProjectUserGrants.PROJECT_USER_GRANTS.GRANTOR_USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field5() {
		return us.fok.lenzenslijper.models.jooq.tables.ProjectUserGrants.PROJECT_USER_GRANTS.CREATED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field6() {
		return us.fok.lenzenslijper.models.jooq.tables.ProjectUserGrants.PROJECT_USER_GRANTS.ROW_CREATED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field7() {
		return us.fok.lenzenslijper.models.jooq.tables.ProjectUserGrants.PROJECT_USER_GRANTS.ROW_UPDATED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value1() {
		return getProjectId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value2() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getProjectRoleId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value4() {
		return getGrantorUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value5() {
		return getCreated();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value6() {
		return getRowCreated();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value7() {
		return getRowUpdated();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProjectUserGrantsRecord value1(java.util.UUID value) {
		setProjectId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProjectUserGrantsRecord value2(java.util.UUID value) {
		setUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProjectUserGrantsRecord value3(java.lang.Integer value) {
		setProjectRoleId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProjectUserGrantsRecord value4(java.util.UUID value) {
		setGrantorUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProjectUserGrantsRecord value5(java.sql.Timestamp value) {
		setCreated(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProjectUserGrantsRecord value6(java.sql.Timestamp value) {
		setRowCreated(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProjectUserGrantsRecord value7(java.sql.Timestamp value) {
		setRowUpdated(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProjectUserGrantsRecord values(java.util.UUID value1, java.util.UUID value2, java.lang.Integer value3, java.util.UUID value4, java.sql.Timestamp value5, java.sql.Timestamp value6, java.sql.Timestamp value7) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ProjectUserGrantsRecord
	 */
	public ProjectUserGrantsRecord() {
		super(us.fok.lenzenslijper.models.jooq.tables.ProjectUserGrants.PROJECT_USER_GRANTS);
	}

	/**
	 * Create a detached, initialised ProjectUserGrantsRecord
	 */
	public ProjectUserGrantsRecord(java.util.UUID projectId, java.util.UUID userId, java.lang.Integer projectRoleId, java.util.UUID grantorUserId, java.sql.Timestamp created, java.sql.Timestamp rowCreated, java.sql.Timestamp rowUpdated) {
		super(us.fok.lenzenslijper.models.jooq.tables.ProjectUserGrants.PROJECT_USER_GRANTS);

		setValue(0, projectId);
		setValue(1, userId);
		setValue(2, projectRoleId);
		setValue(3, grantorUserId);
		setValue(4, created);
		setValue(5, rowCreated);
		setValue(6, rowUpdated);
	}
}
