/**
 * This class is generated by jOOQ
 */
package us.fok.lenzenslijper.models.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ReleasedTitleSummariesRecord extends org.jooq.impl.UpdatableRecordImpl<us.fok.lenzenslijper.models.jooq.tables.records.ReleasedTitleSummariesRecord> implements org.jooq.Record3<java.lang.Integer, java.util.UUID, java.lang.String> {

	private static final long serialVersionUID = -1505310577;

	/**
	 * Setter for <code>public.released_title_summaries.release_tag_id</code>.
	 */
	public void setReleaseTagId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.released_title_summaries.release_tag_id</code>.
	 */
	public java.lang.Integer getReleaseTagId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.released_title_summaries.document_id</code>.
	 */
	public void setDocumentId(java.util.UUID value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.released_title_summaries.document_id</code>.
	 */
	public java.util.UUID getDocumentId() {
		return (java.util.UUID) getValue(1);
	}

	/**
	 * Setter for <code>public.released_title_summaries.title</code>.
	 */
	public void setTitle(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.released_title_summaries.title</code>.
	 */
	public java.lang.String getTitle() {
		return (java.lang.String) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record3<java.lang.Integer, java.util.UUID, java.lang.String> key() {
		return (org.jooq.Record3) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.util.UUID, java.lang.String> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.util.UUID, java.lang.String> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return us.fok.lenzenslijper.models.jooq.tables.ReleasedTitleSummaries.RELEASED_TITLE_SUMMARIES.RELEASE_TAG_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field2() {
		return us.fok.lenzenslijper.models.jooq.tables.ReleasedTitleSummaries.RELEASED_TITLE_SUMMARIES.DOCUMENT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return us.fok.lenzenslijper.models.jooq.tables.ReleasedTitleSummaries.RELEASED_TITLE_SUMMARIES.TITLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getReleaseTagId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value2() {
		return getDocumentId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getTitle();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ReleasedTitleSummariesRecord value1(java.lang.Integer value) {
		setReleaseTagId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ReleasedTitleSummariesRecord value2(java.util.UUID value) {
		setDocumentId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ReleasedTitleSummariesRecord value3(java.lang.String value) {
		setTitle(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ReleasedTitleSummariesRecord values(java.lang.Integer value1, java.util.UUID value2, java.lang.String value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ReleasedTitleSummariesRecord
	 */
	public ReleasedTitleSummariesRecord() {
		super(us.fok.lenzenslijper.models.jooq.tables.ReleasedTitleSummaries.RELEASED_TITLE_SUMMARIES);
	}

	/**
	 * Create a detached, initialised ReleasedTitleSummariesRecord
	 */
	public ReleasedTitleSummariesRecord(java.lang.Integer releaseTagId, java.util.UUID documentId, java.lang.String title) {
		super(us.fok.lenzenslijper.models.jooq.tables.ReleasedTitleSummaries.RELEASED_TITLE_SUMMARIES);

		setValue(0, releaseTagId);
		setValue(1, documentId);
		setValue(2, title);
	}
}
