/**
 * This class is generated by jOOQ
 */
package us.fok.lenzenslijper.models.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ReleasedRevisionSummariesRecord extends org.jooq.impl.UpdatableRecordImpl<us.fok.lenzenslijper.models.jooq.tables.records.ReleasedRevisionSummariesRecord> implements org.jooq.Record5<java.util.UUID, java.lang.Integer, java.util.UUID, java.sql.Timestamp, java.sql.Timestamp> {

	private static final long serialVersionUID = 812504057;

	/**
	 * Setter for <code>public.released_revision_summaries.revision_id</code>.
	 */
	public void setRevisionId(java.util.UUID value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.released_revision_summaries.revision_id</code>.
	 */
	public java.util.UUID getRevisionId() {
		return (java.util.UUID) getValue(0);
	}

	/**
	 * Setter for <code>public.released_revision_summaries.release_tag_id</code>.
	 */
	public void setReleaseTagId(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.released_revision_summaries.release_tag_id</code>.
	 */
	public java.lang.Integer getReleaseTagId() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>public.released_revision_summaries.document_id</code>.
	 */
	public void setDocumentId(java.util.UUID value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.released_revision_summaries.document_id</code>.
	 */
	public java.util.UUID getDocumentId() {
		return (java.util.UUID) getValue(2);
	}

	/**
	 * Setter for <code>public.released_revision_summaries.created</code>.
	 */
	public void setCreated(java.sql.Timestamp value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.released_revision_summaries.created</code>.
	 */
	public java.sql.Timestamp getCreated() {
		return (java.sql.Timestamp) getValue(3);
	}

	/**
	 * Setter for <code>public.released_revision_summaries.assessed</code>.
	 */
	public void setAssessed(java.sql.Timestamp value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.released_revision_summaries.assessed</code>.
	 */
	public java.sql.Timestamp getAssessed() {
		return (java.sql.Timestamp) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record2<java.util.UUID, java.lang.Integer> key() {
		return (org.jooq.Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.util.UUID, java.lang.Integer, java.util.UUID, java.sql.Timestamp, java.sql.Timestamp> fieldsRow() {
		return (org.jooq.Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.util.UUID, java.lang.Integer, java.util.UUID, java.sql.Timestamp, java.sql.Timestamp> valuesRow() {
		return (org.jooq.Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field1() {
		return us.fok.lenzenslijper.models.jooq.tables.ReleasedRevisionSummaries.RELEASED_REVISION_SUMMARIES.REVISION_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return us.fok.lenzenslijper.models.jooq.tables.ReleasedRevisionSummaries.RELEASED_REVISION_SUMMARIES.RELEASE_TAG_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field3() {
		return us.fok.lenzenslijper.models.jooq.tables.ReleasedRevisionSummaries.RELEASED_REVISION_SUMMARIES.DOCUMENT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field4() {
		return us.fok.lenzenslijper.models.jooq.tables.ReleasedRevisionSummaries.RELEASED_REVISION_SUMMARIES.CREATED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field5() {
		return us.fok.lenzenslijper.models.jooq.tables.ReleasedRevisionSummaries.RELEASED_REVISION_SUMMARIES.ASSESSED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value1() {
		return getRevisionId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getReleaseTagId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value3() {
		return getDocumentId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value4() {
		return getCreated();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value5() {
		return getAssessed();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ReleasedRevisionSummariesRecord value1(java.util.UUID value) {
		setRevisionId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ReleasedRevisionSummariesRecord value2(java.lang.Integer value) {
		setReleaseTagId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ReleasedRevisionSummariesRecord value3(java.util.UUID value) {
		setDocumentId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ReleasedRevisionSummariesRecord value4(java.sql.Timestamp value) {
		setCreated(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ReleasedRevisionSummariesRecord value5(java.sql.Timestamp value) {
		setAssessed(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ReleasedRevisionSummariesRecord values(java.util.UUID value1, java.lang.Integer value2, java.util.UUID value3, java.sql.Timestamp value4, java.sql.Timestamp value5) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ReleasedRevisionSummariesRecord
	 */
	public ReleasedRevisionSummariesRecord() {
		super(us.fok.lenzenslijper.models.jooq.tables.ReleasedRevisionSummaries.RELEASED_REVISION_SUMMARIES);
	}

	/**
	 * Create a detached, initialised ReleasedRevisionSummariesRecord
	 */
	public ReleasedRevisionSummariesRecord(java.util.UUID revisionId, java.lang.Integer releaseTagId, java.util.UUID documentId, java.sql.Timestamp created, java.sql.Timestamp assessed) {
		super(us.fok.lenzenslijper.models.jooq.tables.ReleasedRevisionSummaries.RELEASED_REVISION_SUMMARIES);

		setValue(0, revisionId);
		setValue(1, releaseTagId);
		setValue(2, documentId);
		setValue(3, created);
		setValue(4, assessed);
	}
}
