/**
 * This class is generated by jOOQ
 */
package us.fok.lenzenslijper.models.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RevisionAssetRolesRecord extends org.jooq.impl.UpdatableRecordImpl<us.fok.lenzenslijper.models.jooq.tables.records.RevisionAssetRolesRecord> implements org.jooq.Record6<java.util.UUID, java.util.UUID, java.lang.Integer, java.lang.String, java.sql.Timestamp, java.sql.Timestamp> {

	private static final long serialVersionUID = 1683030769;

	/**
	 * Setter for <code>public.revision_asset_roles.revision_id</code>.
	 */
	public void setRevisionId(java.util.UUID value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.revision_asset_roles.revision_id</code>.
	 */
	public java.util.UUID getRevisionId() {
		return (java.util.UUID) getValue(0);
	}

	/**
	 * Setter for <code>public.revision_asset_roles.asset_id</code>.
	 */
	public void setAssetId(java.util.UUID value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.revision_asset_roles.asset_id</code>.
	 */
	public java.util.UUID getAssetId() {
		return (java.util.UUID) getValue(1);
	}

	/**
	 * Setter for <code>public.revision_asset_roles.asset_role_id</code>.
	 */
	public void setAssetRoleId(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.revision_asset_roles.asset_role_id</code>.
	 */
	public java.lang.Integer getAssetRoleId() {
		return (java.lang.Integer) getValue(2);
	}

	/**
	 * Setter for <code>public.revision_asset_roles.title</code>.
	 */
	public void setTitle(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.revision_asset_roles.title</code>.
	 */
	public java.lang.String getTitle() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>public.revision_asset_roles.row_created</code>.
	 */
	public void setRowCreated(java.sql.Timestamp value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.revision_asset_roles.row_created</code>.
	 */
	public java.sql.Timestamp getRowCreated() {
		return (java.sql.Timestamp) getValue(4);
	}

	/**
	 * Setter for <code>public.revision_asset_roles.row_updated</code>.
	 */
	public void setRowUpdated(java.sql.Timestamp value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.revision_asset_roles.row_updated</code>.
	 */
	public java.sql.Timestamp getRowUpdated() {
		return (java.sql.Timestamp) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record3<java.util.UUID, java.lang.Integer, java.lang.String> key() {
		return (org.jooq.Record3) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.util.UUID, java.util.UUID, java.lang.Integer, java.lang.String, java.sql.Timestamp, java.sql.Timestamp> fieldsRow() {
		return (org.jooq.Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.util.UUID, java.util.UUID, java.lang.Integer, java.lang.String, java.sql.Timestamp, java.sql.Timestamp> valuesRow() {
		return (org.jooq.Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field1() {
		return us.fok.lenzenslijper.models.jooq.tables.RevisionAssetRoles.REVISION_ASSET_ROLES.REVISION_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field2() {
		return us.fok.lenzenslijper.models.jooq.tables.RevisionAssetRoles.REVISION_ASSET_ROLES.ASSET_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return us.fok.lenzenslijper.models.jooq.tables.RevisionAssetRoles.REVISION_ASSET_ROLES.ASSET_ROLE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return us.fok.lenzenslijper.models.jooq.tables.RevisionAssetRoles.REVISION_ASSET_ROLES.TITLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field5() {
		return us.fok.lenzenslijper.models.jooq.tables.RevisionAssetRoles.REVISION_ASSET_ROLES.ROW_CREATED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field6() {
		return us.fok.lenzenslijper.models.jooq.tables.RevisionAssetRoles.REVISION_ASSET_ROLES.ROW_UPDATED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value1() {
		return getRevisionId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value2() {
		return getAssetId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getAssetRoleId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getTitle();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value5() {
		return getRowCreated();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value6() {
		return getRowUpdated();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RevisionAssetRolesRecord value1(java.util.UUID value) {
		setRevisionId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RevisionAssetRolesRecord value2(java.util.UUID value) {
		setAssetId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RevisionAssetRolesRecord value3(java.lang.Integer value) {
		setAssetRoleId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RevisionAssetRolesRecord value4(java.lang.String value) {
		setTitle(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RevisionAssetRolesRecord value5(java.sql.Timestamp value) {
		setRowCreated(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RevisionAssetRolesRecord value6(java.sql.Timestamp value) {
		setRowUpdated(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RevisionAssetRolesRecord values(java.util.UUID value1, java.util.UUID value2, java.lang.Integer value3, java.lang.String value4, java.sql.Timestamp value5, java.sql.Timestamp value6) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached RevisionAssetRolesRecord
	 */
	public RevisionAssetRolesRecord() {
		super(us.fok.lenzenslijper.models.jooq.tables.RevisionAssetRoles.REVISION_ASSET_ROLES);
	}

	/**
	 * Create a detached, initialised RevisionAssetRolesRecord
	 */
	public RevisionAssetRolesRecord(java.util.UUID revisionId, java.util.UUID assetId, java.lang.Integer assetRoleId, java.lang.String title, java.sql.Timestamp rowCreated, java.sql.Timestamp rowUpdated) {
		super(us.fok.lenzenslijper.models.jooq.tables.RevisionAssetRoles.REVISION_ASSET_ROLES);

		setValue(0, revisionId);
		setValue(1, assetId);
		setValue(2, assetRoleId);
		setValue(3, title);
		setValue(4, rowCreated);
		setValue(5, rowUpdated);
	}
}
