/**
 * This class is generated by jOOQ
 */
package us.fok.lenzenslijper.models.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SpatialRefSysRecord extends org.jooq.impl.UpdatableRecordImpl<us.fok.lenzenslijper.models.jooq.tables.records.SpatialRefSysRecord> implements org.jooq.Record5<java.lang.Integer, java.lang.String, java.lang.Integer, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = -548973829;

	/**
	 * Setter for <code>public.spatial_ref_sys.srid</code>.
	 */
	public void setSrid(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.spatial_ref_sys.srid</code>.
	 */
	public java.lang.Integer getSrid() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.spatial_ref_sys.auth_name</code>.
	 */
	public void setAuthName(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.spatial_ref_sys.auth_name</code>.
	 */
	public java.lang.String getAuthName() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>public.spatial_ref_sys.auth_srid</code>.
	 */
	public void setAuthSrid(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.spatial_ref_sys.auth_srid</code>.
	 */
	public java.lang.Integer getAuthSrid() {
		return (java.lang.Integer) getValue(2);
	}

	/**
	 * Setter for <code>public.spatial_ref_sys.srtext</code>.
	 */
	public void setSrtext(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.spatial_ref_sys.srtext</code>.
	 */
	public java.lang.String getSrtext() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>public.spatial_ref_sys.proj4text</code>.
	 */
	public void setProj4text(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.spatial_ref_sys.proj4text</code>.
	 */
	public java.lang.String getProj4text() {
		return (java.lang.String) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Integer, java.lang.String, java.lang.Integer, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Integer, java.lang.String, java.lang.Integer, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return us.fok.lenzenslijper.models.jooq.tables.SpatialRefSys.SPATIAL_REF_SYS.SRID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return us.fok.lenzenslijper.models.jooq.tables.SpatialRefSys.SPATIAL_REF_SYS.AUTH_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return us.fok.lenzenslijper.models.jooq.tables.SpatialRefSys.SPATIAL_REF_SYS.AUTH_SRID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return us.fok.lenzenslijper.models.jooq.tables.SpatialRefSys.SPATIAL_REF_SYS.SRTEXT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return us.fok.lenzenslijper.models.jooq.tables.SpatialRefSys.SPATIAL_REF_SYS.PROJ4TEXT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getSrid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getAuthName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getAuthSrid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getSrtext();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getProj4text();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SpatialRefSysRecord value1(java.lang.Integer value) {
		setSrid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SpatialRefSysRecord value2(java.lang.String value) {
		setAuthName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SpatialRefSysRecord value3(java.lang.Integer value) {
		setAuthSrid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SpatialRefSysRecord value4(java.lang.String value) {
		setSrtext(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SpatialRefSysRecord value5(java.lang.String value) {
		setProj4text(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SpatialRefSysRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.Integer value3, java.lang.String value4, java.lang.String value5) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached SpatialRefSysRecord
	 */
	public SpatialRefSysRecord() {
		super(us.fok.lenzenslijper.models.jooq.tables.SpatialRefSys.SPATIAL_REF_SYS);
	}

	/**
	 * Create a detached, initialised SpatialRefSysRecord
	 */
	public SpatialRefSysRecord(java.lang.Integer srid, java.lang.String authName, java.lang.Integer authSrid, java.lang.String srtext, java.lang.String proj4text) {
		super(us.fok.lenzenslijper.models.jooq.tables.SpatialRefSys.SPATIAL_REF_SYS);

		setValue(0, srid);
		setValue(1, authName);
		setValue(2, authSrid);
		setValue(3, srtext);
		setValue(4, proj4text);
	}
}
