/**
 * This class is generated by jOOQ
 */
package us.fok.lenzenslijper.models.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsersRecord extends org.jooq.impl.UpdatableRecordImpl<us.fok.lenzenslijper.models.jooq.tables.records.UsersRecord> {

	private static final long serialVersionUID = 883845344;

	/**
	 * Setter for <code>public.users.user_id</code>.
	 */
	public void setUserId(java.util.UUID value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.users.user_id</code>.
	 */
	public java.util.UUID getUserId() {
		return (java.util.UUID) getValue(0);
	}

	/**
	 * Setter for <code>public.users.username</code>.
	 */
	public void setUsername(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.users.username</code>.
	 */
	public java.lang.String getUsername() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>public.users.encrypted_password</code>.
	 */
	public void setEncryptedPassword(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.users.encrypted_password</code>.
	 */
	public java.lang.String getEncryptedPassword() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>public.users.reset_password_token</code>.
	 */
	public void setResetPasswordToken(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.users.reset_password_token</code>.
	 */
	public java.lang.String getResetPasswordToken() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>public.users.reset_password_sent_at</code>.
	 */
	public void setResetPasswordSentAt(java.sql.Timestamp value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.users.reset_password_sent_at</code>.
	 */
	public java.sql.Timestamp getResetPasswordSentAt() {
		return (java.sql.Timestamp) getValue(4);
	}

	/**
	 * Setter for <code>public.users.remember_created_at</code>.
	 */
	public void setRememberCreatedAt(java.sql.Timestamp value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.users.remember_created_at</code>.
	 */
	public java.sql.Timestamp getRememberCreatedAt() {
		return (java.sql.Timestamp) getValue(5);
	}

	/**
	 * Setter for <code>public.users.remember_token</code>.
	 */
	public void setRememberToken(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>public.users.remember_token</code>.
	 */
	public java.lang.String getRememberToken() {
		return (java.lang.String) getValue(6);
	}

	/**
	 * Setter for <code>public.users.sign_in_count</code>.
	 */
	public void setSignInCount(java.lang.Integer value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>public.users.sign_in_count</code>.
	 */
	public java.lang.Integer getSignInCount() {
		return (java.lang.Integer) getValue(7);
	}

	/**
	 * Setter for <code>public.users.current_sign_in_at</code>.
	 */
	public void setCurrentSignInAt(java.sql.Timestamp value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>public.users.current_sign_in_at</code>.
	 */
	public java.sql.Timestamp getCurrentSignInAt() {
		return (java.sql.Timestamp) getValue(8);
	}

	/**
	 * Setter for <code>public.users.current_sign_in_ip</code>.
	 */
	public void setCurrentSignInIp(java.lang.String value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>public.users.current_sign_in_ip</code>.
	 */
	public java.lang.String getCurrentSignInIp() {
		return (java.lang.String) getValue(9);
	}

	/**
	 * Setter for <code>public.users.last_sign_in_at</code>.
	 */
	public void setLastSignInAt(java.sql.Timestamp value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>public.users.last_sign_in_at</code>.
	 */
	public java.sql.Timestamp getLastSignInAt() {
		return (java.sql.Timestamp) getValue(10);
	}

	/**
	 * Setter for <code>public.users.last_sign_in_ip</code>.
	 */
	public void setLastSignInIp(java.lang.String value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>public.users.last_sign_in_ip</code>.
	 */
	public java.lang.String getLastSignInIp() {
		return (java.lang.String) getValue(11);
	}

	/**
	 * Setter for <code>public.users.confirmation_token</code>.
	 */
	public void setConfirmationToken(java.lang.String value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>public.users.confirmation_token</code>.
	 */
	public java.lang.String getConfirmationToken() {
		return (java.lang.String) getValue(12);
	}

	/**
	 * Setter for <code>public.users.confirmation_sent_at</code>.
	 */
	public void setConfirmationSentAt(java.sql.Timestamp value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>public.users.confirmation_sent_at</code>.
	 */
	public java.sql.Timestamp getConfirmationSentAt() {
		return (java.sql.Timestamp) getValue(13);
	}

	/**
	 * Setter for <code>public.users.confirmed_at</code>.
	 */
	public void setConfirmedAt(java.sql.Timestamp value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>public.users.confirmed_at</code>.
	 */
	public java.sql.Timestamp getConfirmedAt() {
		return (java.sql.Timestamp) getValue(14);
	}

	/**
	 * Setter for <code>public.users.unconfirmed_email</code>.
	 */
	public void setUnconfirmedEmail(java.lang.String value) {
		setValue(15, value);
	}

	/**
	 * Getter for <code>public.users.unconfirmed_email</code>.
	 */
	public java.lang.String getUnconfirmedEmail() {
		return (java.lang.String) getValue(15);
	}

	/**
	 * Setter for <code>public.users.invitation_token</code>.
	 */
	public void setInvitationToken(java.lang.String value) {
		setValue(16, value);
	}

	/**
	 * Getter for <code>public.users.invitation_token</code>.
	 */
	public java.lang.String getInvitationToken() {
		return (java.lang.String) getValue(16);
	}

	/**
	 * Setter for <code>public.users.invitation_sent_at</code>.
	 */
	public void setInvitationSentAt(java.sql.Timestamp value) {
		setValue(17, value);
	}

	/**
	 * Getter for <code>public.users.invitation_sent_at</code>.
	 */
	public java.sql.Timestamp getInvitationSentAt() {
		return (java.sql.Timestamp) getValue(17);
	}

	/**
	 * Setter for <code>public.users.invitation_accepted_at</code>.
	 */
	public void setInvitationAcceptedAt(java.sql.Timestamp value) {
		setValue(18, value);
	}

	/**
	 * Getter for <code>public.users.invitation_accepted_at</code>.
	 */
	public java.sql.Timestamp getInvitationAcceptedAt() {
		return (java.sql.Timestamp) getValue(18);
	}

	/**
	 * Setter for <code>public.users.invited_by_id</code>.
	 */
	public void setInvitedById(java.util.UUID value) {
		setValue(19, value);
	}

	/**
	 * Getter for <code>public.users.invited_by_id</code>.
	 */
	public java.util.UUID getInvitedById() {
		return (java.util.UUID) getValue(19);
	}

	/**
	 * Setter for <code>public.users.invited_by_type</code>.
	 */
	public void setInvitedByType(java.lang.String value) {
		setValue(20, value);
	}

	/**
	 * Getter for <code>public.users.invited_by_type</code>.
	 */
	public java.lang.String getInvitedByType() {
		return (java.lang.String) getValue(20);
	}

	/**
	 * Setter for <code>public.users.invitation_limit</code>.
	 */
	public void setInvitationLimit(java.lang.Integer value) {
		setValue(21, value);
	}

	/**
	 * Getter for <code>public.users.invitation_limit</code>.
	 */
	public java.lang.Integer getInvitationLimit() {
		return (java.lang.Integer) getValue(21);
	}

	/**
	 * Setter for <code>public.users.api_token</code>.
	 */
	public void setApiToken(java.lang.String value) {
		setValue(22, value);
	}

	/**
	 * Getter for <code>public.users.api_token</code>.
	 */
	public java.lang.String getApiToken() {
		return (java.lang.String) getValue(22);
	}

	/**
	 * Setter for <code>public.users.name</code>.
	 */
	public void setName(java.lang.String value) {
		setValue(23, value);
	}

	/**
	 * Getter for <code>public.users.name</code>.
	 */
	public java.lang.String getName() {
		return (java.lang.String) getValue(23);
	}

	/**
	 * Setter for <code>public.users.email</code>.
	 */
	public void setEmail(java.lang.String value) {
		setValue(24, value);
	}

	/**
	 * Getter for <code>public.users.email</code>.
	 */
	public java.lang.String getEmail() {
		return (java.lang.String) getValue(24);
	}

	/**
	 * Setter for <code>public.users.status</code>.
	 */
	public void setStatus(java.lang.String value) {
		setValue(25, value);
	}

	/**
	 * Getter for <code>public.users.status</code>.
	 */
	public java.lang.String getStatus() {
		return (java.lang.String) getValue(25);
	}

	/**
	 * Setter for <code>public.users.created</code>.
	 */
	public void setCreated(java.sql.Timestamp value) {
		setValue(26, value);
	}

	/**
	 * Getter for <code>public.users.created</code>.
	 */
	public java.sql.Timestamp getCreated() {
		return (java.sql.Timestamp) getValue(26);
	}

	/**
	 * Setter for <code>public.users.row_created</code>.
	 */
	public void setRowCreated(java.sql.Timestamp value) {
		setValue(27, value);
	}

	/**
	 * Getter for <code>public.users.row_created</code>.
	 */
	public java.sql.Timestamp getRowCreated() {
		return (java.sql.Timestamp) getValue(27);
	}

	/**
	 * Setter for <code>public.users.row_updated</code>.
	 */
	public void setRowUpdated(java.sql.Timestamp value) {
		setValue(28, value);
	}

	/**
	 * Getter for <code>public.users.row_updated</code>.
	 */
	public java.sql.Timestamp getRowUpdated() {
		return (java.sql.Timestamp) getValue(28);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.util.UUID> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached UsersRecord
	 */
	public UsersRecord() {
		super(us.fok.lenzenslijper.models.jooq.tables.Users.USERS);
	}

	/**
	 * Create a detached, initialised UsersRecord
	 */
	public UsersRecord(java.util.UUID userId, java.lang.String username, java.lang.String encryptedPassword, java.lang.String resetPasswordToken, java.sql.Timestamp resetPasswordSentAt, java.sql.Timestamp rememberCreatedAt, java.lang.String rememberToken, java.lang.Integer signInCount, java.sql.Timestamp currentSignInAt, java.lang.String currentSignInIp, java.sql.Timestamp lastSignInAt, java.lang.String lastSignInIp, java.lang.String confirmationToken, java.sql.Timestamp confirmationSentAt, java.sql.Timestamp confirmedAt, java.lang.String unconfirmedEmail, java.lang.String invitationToken, java.sql.Timestamp invitationSentAt, java.sql.Timestamp invitationAcceptedAt, java.util.UUID invitedById, java.lang.String invitedByType, java.lang.Integer invitationLimit, java.lang.String apiToken, java.lang.String name, java.lang.String email, java.lang.String status, java.sql.Timestamp created, java.sql.Timestamp rowCreated, java.sql.Timestamp rowUpdated) {
		super(us.fok.lenzenslijper.models.jooq.tables.Users.USERS);

		setValue(0, userId);
		setValue(1, username);
		setValue(2, encryptedPassword);
		setValue(3, resetPasswordToken);
		setValue(4, resetPasswordSentAt);
		setValue(5, rememberCreatedAt);
		setValue(6, rememberToken);
		setValue(7, signInCount);
		setValue(8, currentSignInAt);
		setValue(9, currentSignInIp);
		setValue(10, lastSignInAt);
		setValue(11, lastSignInIp);
		setValue(12, confirmationToken);
		setValue(13, confirmationSentAt);
		setValue(14, confirmedAt);
		setValue(15, unconfirmedEmail);
		setValue(16, invitationToken);
		setValue(17, invitationSentAt);
		setValue(18, invitationAcceptedAt);
		setValue(19, invitedById);
		setValue(20, invitedByType);
		setValue(21, invitationLimit);
		setValue(22, apiToken);
		setValue(23, name);
		setValue(24, email);
		setValue(25, status);
		setValue(26, created);
		setValue(27, rowCreated);
		setValue(28, rowUpdated);
	}
}
