/**
 * This class is generated by jOOQ
 */
package us.fok.lenzenslijper.models.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VirtualAggregateGrantsRecord extends org.jooq.impl.TableRecordImpl<us.fok.lenzenslijper.models.jooq.tables.records.VirtualAggregateGrantsRecord> implements org.jooq.Record3<java.util.UUID, java.util.UUID, java.lang.Integer> {

	private static final long serialVersionUID = 287907484;

	/**
	 * Setter for <code>public.virtual_aggregate_grants.user_id</code>.
	 */
	public void setUserId(java.util.UUID value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.virtual_aggregate_grants.user_id</code>.
	 */
	public java.util.UUID getUserId() {
		return (java.util.UUID) getValue(0);
	}

	/**
	 * Setter for <code>public.virtual_aggregate_grants.project_id</code>.
	 */
	public void setProjectId(java.util.UUID value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.virtual_aggregate_grants.project_id</code>.
	 */
	public java.util.UUID getProjectId() {
		return (java.util.UUID) getValue(1);
	}

	/**
	 * Setter for <code>public.virtual_aggregate_grants.mode</code>.
	 */
	public void setMode(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.virtual_aggregate_grants.mode</code>.
	 */
	public java.lang.Integer getMode() {
		return (java.lang.Integer) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.util.UUID, java.util.UUID, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.util.UUID, java.util.UUID, java.lang.Integer> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field1() {
		return us.fok.lenzenslijper.models.jooq.tables.VirtualAggregateGrants.VIRTUAL_AGGREGATE_GRANTS.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field2() {
		return us.fok.lenzenslijper.models.jooq.tables.VirtualAggregateGrants.VIRTUAL_AGGREGATE_GRANTS.PROJECT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return us.fok.lenzenslijper.models.jooq.tables.VirtualAggregateGrants.VIRTUAL_AGGREGATE_GRANTS.MODE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value1() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value2() {
		return getProjectId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getMode();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public VirtualAggregateGrantsRecord value1(java.util.UUID value) {
		setUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public VirtualAggregateGrantsRecord value2(java.util.UUID value) {
		setProjectId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public VirtualAggregateGrantsRecord value3(java.lang.Integer value) {
		setMode(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public VirtualAggregateGrantsRecord values(java.util.UUID value1, java.util.UUID value2, java.lang.Integer value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached VirtualAggregateGrantsRecord
	 */
	public VirtualAggregateGrantsRecord() {
		super(us.fok.lenzenslijper.models.jooq.tables.VirtualAggregateGrants.VIRTUAL_AGGREGATE_GRANTS);
	}

	/**
	 * Create a detached, initialised VirtualAggregateGrantsRecord
	 */
	public VirtualAggregateGrantsRecord(java.util.UUID userId, java.util.UUID projectId, java.lang.Integer mode) {
		super(us.fok.lenzenslijper.models.jooq.tables.VirtualAggregateGrants.VIRTUAL_AGGREGATE_GRANTS);

		setValue(0, userId);
		setValue(1, projectId);
		setValue(2, mode);
	}
}
